-- +goose Up
DROP TRIGGER IF EXISTS trg_sync_player_character_stats_after_update;
DROP TRIGGER IF EXISTS trg_sync_player_character_stats_after_insert;
DROP TRIGGER IF EXISTS trg_sync_combatant_stats_after_update;
DROP TRIGGER IF EXISTS trg_sync_combatant_stats_after_insert;

ALTER TABLE combatants DROP COLUMN defense_head;
ALTER TABLE combatants DROP COLUMN defense_torso;
ALTER TABLE combatants DROP COLUMN defense_left_arm;
ALTER TABLE combatants DROP COLUMN defense_right_arm;
ALTER TABLE combatants DROP COLUMN defense_left_leg;
ALTER TABLE combatants DROP COLUMN defense_right_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_head;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_torso;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_left_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_right_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_left_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_right_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation;
ALTER TABLE combatants DROP COLUMN damage_resistance_poison;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_head;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_torso;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_left_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_right_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_left_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_right_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_head;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_torso;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_left_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_right_arm;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_left_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_right_leg;
ALTER TABLE combatants DROP COLUMN damage_resistance_physical_immune;
ALTER TABLE combatants DROP COLUMN damage_resistance_energy_immune;
ALTER TABLE combatants DROP COLUMN damage_resistance_radiation_immune;
ALTER TABLE combatants DROP COLUMN damage_resistance_poison_immune;

ALTER TABLE player_characters DROP COLUMN defense_head;
ALTER TABLE player_characters DROP COLUMN defense_torso;
ALTER TABLE player_characters DROP COLUMN defense_left_arm;
ALTER TABLE player_characters DROP COLUMN defense_right_arm;
ALTER TABLE player_characters DROP COLUMN defense_left_leg;
ALTER TABLE player_characters DROP COLUMN defense_right_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_head;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_torso;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_left_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_right_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_left_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_right_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation;
ALTER TABLE player_characters DROP COLUMN damage_resistance_poison;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_head;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_torso;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_left_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_right_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_left_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_right_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_head;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_torso;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_left_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_right_arm;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_left_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_right_leg;
ALTER TABLE player_characters DROP COLUMN damage_resistance_physical_immune;
ALTER TABLE player_characters DROP COLUMN damage_resistance_energy_immune;
ALTER TABLE player_characters DROP COLUMN damage_resistance_radiation_immune;
ALTER TABLE player_characters DROP COLUMN damage_resistance_poison_immune;

-- +goose Down
ALTER TABLE combatants ADD COLUMN defense_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN defense_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN defense_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN defense_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN defense_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN defense_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_poison INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_physical_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_energy_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_radiation_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE combatants ADD COLUMN damage_resistance_poison_immune INTEGER NOT NULL DEFAULT 0;

ALTER TABLE player_characters ADD COLUMN defense_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN defense_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN defense_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN defense_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN defense_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN defense_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_poison INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_head INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_torso INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_left_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_right_arm INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_left_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_right_leg INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_physical_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_energy_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_radiation_immune INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_characters ADD COLUMN damage_resistance_poison_immune INTEGER NOT NULL DEFAULT 0;
