// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbgen

import (
	"time"
)

type AppState struct {
	ID               int64
	ActiveCampaignID interface{}
}

type Campaign struct {
	ID        string
	Name      string
	StartDate string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Combatant struct {
	ID                              string
	EncounterID                     string
	Name                            string
	Side                            string
	Initiative                      int64
	Active                          int64
	Defeated                        int64
	Position                        int64
	Hp                              int64
	Defense                         int64
	DamageResistance                int64
	DamageResistancePhysical        int64
	DamageResistanceEnergy          int64
	DamageResistanceRadiation       int64
	DamageResistancePoison          int64
	DamageResistancePhysicalImmune  int64
	DamageResistanceEnergyImmune    int64
	DamageResistanceRadiationImmune int64
	DamageResistancePoisonImmune    int64
	Level                           int64
	Xp                              int64
}

type Encounter struct {
	ID         string
	CampaignID interface{}
	Name       string
	Round      int64
	TurnIndex  int64
	PartyAp    int64
	GmThreat   int64
	UpdatedAt  time.Time
	DeletedAt  interface{}
}

type EncounterLog struct {
	ID          string
	EncounterID string
	Round       int64
	Message     string
	CreatedAt   time.Time
}

type Player struct {
	ID         string
	CampaignID string
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type PlayerCharacter struct {
	ID                              string
	PlayerID                        string
	CampaignID                      string
	Name                            string
	Level                           int64
	Initiative                      int64
	Hp                              int64
	Defense                         int64
	DamageResistancePhysical        int64
	DamageResistanceEnergy          int64
	DamageResistanceRadiation       int64
	DamageResistancePoison          int64
	DamageResistancePhysicalImmune  int64
	DamageResistanceEnergyImmune    int64
	DamageResistanceRadiationImmune int64
	DamageResistancePoisonImmune    int64
	Active                          int64
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}
