// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type AppState struct {
	ID               int64
	ActiveCampaignID interface{}
	UpdatedAt        time.Time
}

type BodyLocation struct {
	ID   int64
	Code string
}

type Campaign struct {
	ID        string
	Name      string
	StartDate time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt interface{}
}

type Combatant struct {
	ID                string
	EncounterID       string
	PlayerCharacterID interface{}
	Name              string
	Side              string
	TorsoOnly         int64
	Initiative        int64
	Active            int64
	Defeated          int64
	Position          int64
	Hp                int64
	MaxHp             int64
	Defense           int64
	Level             int64
	Xp                int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         interface{}
}

type CombatantResistanceByLocation struct {
	CombatantID    string
	DamageTypeID   int64
	BodyLocationID int64
	Resistance     int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CombatantResistanceGlobal struct {
	CombatantID  string
	DamageTypeID int64
	Resistance   int64
	Immune       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type DamageType struct {
	ID   int64
	Code string
}

type Encounter struct {
	ID              string
	CampaignID      interface{}
	Name            string
	Round           int64
	TurnIndex       int64
	PartyAp         int64
	GmThreat        int64
	DifficultyLabel string
	DifficultyScore float64
	PartyCount      int64
	PartyAvgLevel   float64
	PartyXpBudget   int64
	EnemyCount      int64
	EnemyAvgLevel   float64
	EnemyTotalXp    int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       interface{}
}

type EncounterLog struct {
	ID          string
	EncounterID string
	Round       int64
	Message     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   interface{}
}

type Player struct {
	ID         string
	CampaignID string
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  interface{}
}

type PlayerCharacter struct {
	ID                 string
	PlayerID           string
	CampaignID         string
	Name               string
	Level              int64
	Initiative         int64
	Hp                 int64
	MaxHp              int64
	Defense            int64
	TorsoOnly          int64
	Active             int64
	AvailabilityStatus string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          interface{}
}

type PlayerCharacterResistanceByLocation struct {
	PlayerCharacterID string
	DamageTypeID      int64
	BodyLocationID    int64
	Resistance        int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PlayerCharacterResistanceGlobal struct {
	PlayerCharacterID string
	DamageTypeID      int64
	Resistance        int64
	Immune            int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
