// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"
)

const activateEncounterByCampaign = `-- name: ActivateEncounterByCampaign :execrows
UPDATE encounters
SET updated_at = CASE
  WHEN STRFTIME('%Y-%m-%d %H:%M:%f', 'now') <= COALESCE((SELECT MAX(e2.updated_at) FROM encounters e2 WHERE e2.deleted_at IS NULL AND e2.campaign_id = ?1), '')
    THEN STRFTIME(
      '%Y-%m-%d %H:%M:%f',
      COALESCE((SELECT MAX(e3.updated_at) FROM encounters e3 WHERE e3.deleted_at IS NULL AND e3.campaign_id = ?1), STRFTIME('%Y-%m-%d %H:%M:%f', 'now')),
      '+0.001 seconds'
    )
  ELSE STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
END
WHERE encounters.id = ?2 AND encounters.deleted_at IS NULL AND encounters.campaign_id = ?1
`

type ActivateEncounterByCampaignParams struct {
	CampaignID  string
	EncounterID string
}

func (q *Queries) ActivateEncounterByCampaign(ctx context.Context, arg ActivateEncounterByCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateEncounterByCampaign, arg.CampaignID, arg.EncounterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deactivateActiveCharactersByPlayerID = `-- name: DeactivateActiveCharactersByPlayerID :exec
UPDATE player_characters
SET active = 0,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE player_id = ?1
  AND active = 1
`

func (q *Queries) DeactivateActiveCharactersByPlayerID(ctx context.Context, playerID string) error {
	_, err := q.db.ExecContext(ctx, deactivateActiveCharactersByPlayerID, playerID)
	return err
}

const deleteCombatantsByEncounterID = `-- name: DeleteCombatantsByEncounterID :exec
DELETE FROM combatants
WHERE encounter_id = ?1
`

func (q *Queries) DeleteCombatantsByEncounterID(ctx context.Context, encounterID string) error {
	_, err := q.db.ExecContext(ctx, deleteCombatantsByEncounterID, encounterID)
	return err
}

const deletePlayersByCampaignID = `-- name: DeletePlayersByCampaignID :exec
DELETE FROM players
WHERE campaign_id = ?1
`

func (q *Queries) DeletePlayersByCampaignID(ctx context.Context, campaignID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayersByCampaignID, campaignID)
	return err
}

const deleteStatProfileResistancesByProfileID = `-- name: DeleteStatProfileResistancesByProfileID :exec
DELETE FROM stat_profile_resistance_by_location
WHERE stat_profile_id = ?1
`

func (q *Queries) DeleteStatProfileResistancesByProfileID(ctx context.Context, statProfileID string) error {
	_, err := q.db.ExecContext(ctx, deleteStatProfileResistancesByProfileID, statProfileID)
	return err
}

const ensureAppStateRow = `-- name: EnsureAppStateRow :exec
INSERT OR IGNORE INTO app_state (id, active_campaign_id)
VALUES (1, NULL)
`

func (q *Queries) EnsureAppStateRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureAppStateRow)
	return err
}

const getActiveCampaign = `-- name: GetActiveCampaign :one
SELECT c.id, c.name, c.start_date, c.party_ap, c.gm_threat, c.updated_at
FROM campaigns c
JOIN app_state s ON s.id = 1
WHERE c.id = s.active_campaign_id
`

type GetActiveCampaignRow struct {
	ID        string
	Name      string
	StartDate time.Time
	PartyAp   int64
	GmThreat  int64
	UpdatedAt time.Time
}

func (q *Queries) GetActiveCampaign(ctx context.Context) (GetActiveCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCampaign)
	var i GetActiveCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.PartyAp,
		&i.GmThreat,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePlayerCharacterByPlayerID = `-- name: GetActivePlayerCharacterByPlayerID :one
SELECT id, name
FROM player_characters
WHERE player_id = ?1
  AND active = 1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetActivePlayerCharacterByPlayerIDRow struct {
	ID   string
	Name string
}

func (q *Queries) GetActivePlayerCharacterByPlayerID(ctx context.Context, playerID string) (GetActivePlayerCharacterByPlayerIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePlayerCharacterByPlayerID, playerID)
	var i GetActivePlayerCharacterByPlayerIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, start_date, party_ap, gm_threat, updated_at
FROM campaigns
WHERE id = ?1
`

type GetCampaignByIDRow struct {
	ID        string
	Name      string
	StartDate time.Time
	PartyAp   int64
	GmThreat  int64
	UpdatedAt time.Time
}

func (q *Queries) GetCampaignByID(ctx context.Context, campaignID string) (GetCampaignByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, campaignID)
	var i GetCampaignByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.PartyAp,
		&i.GmThreat,
		&i.UpdatedAt,
	)
	return i, err
}

const getEffectiveActiveEncounterIDByCampaignID = `-- name: GetEffectiveActiveEncounterIDByCampaignID :one
SELECT e.id
FROM encounters e
JOIN app_state s ON s.id = 1 AND s.active_campaign_id = e.campaign_id
WHERE e.campaign_id = ?1
  AND e.deleted_at IS NULL
ORDER BY e.updated_at DESC, e.id DESC
LIMIT 1
`

func (q *Queries) GetEffectiveActiveEncounterIDByCampaignID(ctx context.Context, campaignID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveActiveEncounterIDByCampaignID, campaignID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEncounterByIDByCampaignID = `-- name: GetEncounterByIDByCampaignID :one
SELECT e.id, e.campaign_id, e.name, e.round, e.turn_index, c.party_ap, c.gm_threat
FROM encounters e
JOIN campaigns c ON c.id = e.campaign_id
WHERE e.deleted_at IS NULL
  AND e.campaign_id = ?1
  AND e.id = ?2
`

type GetEncounterByIDByCampaignIDParams struct {
	CampaignID  string
	EncounterID string
}

type GetEncounterByIDByCampaignIDRow struct {
	ID         string
	CampaignID string
	Name       string
	Round      int64
	TurnIndex  int64
	PartyAp    int64
	GmThreat   int64
}

func (q *Queries) GetEncounterByIDByCampaignID(ctx context.Context, arg GetEncounterByIDByCampaignIDParams) (GetEncounterByIDByCampaignIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEncounterByIDByCampaignID, arg.CampaignID, arg.EncounterID)
	var i GetEncounterByIDByCampaignIDRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Round,
		&i.TurnIndex,
		&i.PartyAp,
		&i.GmThreat,
	)
	return i, err
}

const getLatestEncounterByCampaignID = `-- name: GetLatestEncounterByCampaignID :one
SELECT e.id, e.campaign_id, e.name, e.round, e.turn_index, c.party_ap, c.gm_threat
FROM encounters e
JOIN campaigns c ON c.id = e.campaign_id
WHERE e.deleted_at IS NULL AND e.campaign_id = ?1
ORDER BY e.updated_at DESC, e.id DESC
LIMIT 1
`

type GetLatestEncounterByCampaignIDRow struct {
	ID         string
	CampaignID string
	Name       string
	Round      int64
	TurnIndex  int64
	PartyAp    int64
	GmThreat   int64
}

func (q *Queries) GetLatestEncounterByCampaignID(ctx context.Context, campaignID string) (GetLatestEncounterByCampaignIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestEncounterByCampaignID, campaignID)
	var i GetLatestEncounterByCampaignIDRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Round,
		&i.TurnIndex,
		&i.PartyAp,
		&i.GmThreat,
	)
	return i, err
}

const getMonsterTemplateIDByName = `-- name: GetMonsterTemplateIDByName :one
SELECT id
FROM monster_templates
WHERE lower(trim(name)) = lower(trim(?1))
`

func (q *Queries) GetMonsterTemplateIDByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMonsterTemplateIDByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCampaign = `-- name: InsertCampaign :exec
INSERT INTO campaigns (id, name, start_date, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertCampaignParams struct {
	ID        string
	Name      string
	StartDate time.Time
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) error {
	_, err := q.db.ExecContext(ctx, insertCampaign, arg.ID, arg.Name, arg.StartDate)
	return err
}

const insertCombatant = `-- name: InsertCombatant :exec
INSERT INTO combatants (
	id, encounter_id, stat_profile_id, player_character_id, name, side, defeated, position, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertCombatantParams struct {
	ID                string
	EncounterID       string
	StatProfileID     string
	PlayerCharacterID interface{}
	Name              string
	Side              string
	Defeated          int64
	Position          int64
}

func (q *Queries) InsertCombatant(ctx context.Context, arg InsertCombatantParams) error {
	_, err := q.db.ExecContext(ctx, insertCombatant,
		arg.ID,
		arg.EncounterID,
		arg.StatProfileID,
		arg.PlayerCharacterID,
		arg.Name,
		arg.Side,
		arg.Defeated,
		arg.Position,
	)
	return err
}

const insertEncounterLog = `-- name: InsertEncounterLog :exec
INSERT INTO encounter_logs (id, encounter_id, round, message, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertEncounterLogParams struct {
	ID          string
	EncounterID string
	Round       int64
	Message     string
}

func (q *Queries) InsertEncounterLog(ctx context.Context, arg InsertEncounterLogParams) error {
	_, err := q.db.ExecContext(ctx, insertEncounterLog,
		arg.ID,
		arg.EncounterID,
		arg.Round,
		arg.Message,
	)
	return err
}

const insertPlayer = `-- name: InsertPlayer :exec
INSERT INTO players (id, campaign_id, name, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertPlayerParams struct {
	ID         string
	CampaignID string
	Name       string
}

func (q *Queries) InsertPlayer(ctx context.Context, arg InsertPlayerParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayer, arg.ID, arg.CampaignID, arg.Name)
	return err
}

const insertPlayerCharacter = `-- name: InsertPlayerCharacter :exec
INSERT INTO player_characters (
  id, player_id, stat_profile_id, name, notes, active, availability_status, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertPlayerCharacterParams struct {
	ID                 string
	PlayerID           string
	StatProfileID      string
	Name               string
	Notes              string
	Active             int64
	AvailabilityStatus string
}

func (q *Queries) InsertPlayerCharacter(ctx context.Context, arg InsertPlayerCharacterParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerCharacter,
		arg.ID,
		arg.PlayerID,
		arg.StatProfileID,
		arg.Name,
		arg.Notes,
		arg.Active,
		arg.AvailabilityStatus,
	)
	return err
}

const listActivePartyCharactersByCampaignID = `-- name: ListActivePartyCharactersByCampaignID :many
SELECT
  pc.id,
  p.name AS player_name,
  pc.name AS character_name,
  pc.notes,
  sp.level,
  sp.initiative,
  sp.hp,
  sp.max_hp,
  sp.defense,
  sp.torso_only,
  pc.availability_status
FROM player_characters pc
JOIN stat_profiles sp ON sp.id = pc.stat_profile_id
JOIN players p ON p.id = pc.player_id
WHERE p.campaign_id = ?1 AND pc.active = 1
ORDER BY p.name COLLATE NOCASE ASC, pc.name COLLATE NOCASE ASC
`

type ListActivePartyCharactersByCampaignIDRow struct {
	ID                 string
	PlayerName         string
	CharacterName      string
	Notes              string
	Level              int64
	Initiative         int64
	Hp                 int64
	MaxHp              int64
	Defense            int64
	TorsoOnly          int64
	AvailabilityStatus string
}

func (q *Queries) ListActivePartyCharactersByCampaignID(ctx context.Context, campaignID string) ([]ListActivePartyCharactersByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePartyCharactersByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePartyCharactersByCampaignIDRow
	for rows.Next() {
		var i ListActivePartyCharactersByCampaignIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.CharacterName,
			&i.Notes,
			&i.Level,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
			&i.AvailabilityStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlayerCharacterResistanceByLocationByCampaignID = `-- name: ListActivePlayerCharacterResistanceByLocationByCampaignID :many
SELECT
  pc.id AS player_character_id,
  dt.code AS damage_type,
  bl.code AS body_location,
  sprl.resistance
FROM player_characters pc
JOIN players p ON p.id = pc.player_id
JOIN stat_profile_resistance_by_location sprl ON sprl.stat_profile_id = pc.stat_profile_id
JOIN damage_types dt ON dt.id = sprl.damage_type_id
JOIN body_locations bl ON bl.id = sprl.body_location_id
WHERE p.campaign_id = ?1
  AND pc.active = 1
  AND bl.code <> 'global'
ORDER BY pc.name COLLATE NOCASE ASC, pc.id DESC, dt.id ASC, bl.id ASC
`

type ListActivePlayerCharacterResistanceByLocationByCampaignIDRow struct {
	PlayerCharacterID string
	DamageType        string
	BodyLocation      string
	Resistance        int64
}

func (q *Queries) ListActivePlayerCharacterResistanceByLocationByCampaignID(ctx context.Context, campaignID string) ([]ListActivePlayerCharacterResistanceByLocationByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlayerCharacterResistanceByLocationByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlayerCharacterResistanceByLocationByCampaignIDRow
	for rows.Next() {
		var i ListActivePlayerCharacterResistanceByLocationByCampaignIDRow
		if err := rows.Scan(
			&i.PlayerCharacterID,
			&i.DamageType,
			&i.BodyLocation,
			&i.Resistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlayerCharacterResistanceGlobalByCampaignID = `-- name: ListActivePlayerCharacterResistanceGlobalByCampaignID :many
SELECT
  pc.id AS player_character_id,
  dt.code AS damage_type,
  sprg.resistance,
  sprg.immune
FROM player_characters pc
JOIN players p ON p.id = pc.player_id
JOIN stat_profile_resistance_by_location sprg ON sprg.stat_profile_id = pc.stat_profile_id
JOIN body_locations bl ON bl.id = sprg.body_location_id
  AND bl.code = 'global'
JOIN damage_types dt ON dt.id = sprg.damage_type_id
WHERE p.campaign_id = ?1
  AND pc.active = 1
ORDER BY pc.name COLLATE NOCASE ASC, pc.id DESC, dt.id ASC
`

type ListActivePlayerCharacterResistanceGlobalByCampaignIDRow struct {
	PlayerCharacterID string
	DamageType        string
	Resistance        int64
	Immune            int64
}

func (q *Queries) ListActivePlayerCharacterResistanceGlobalByCampaignID(ctx context.Context, campaignID string) ([]ListActivePlayerCharacterResistanceGlobalByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlayerCharacterResistanceGlobalByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlayerCharacterResistanceGlobalByCampaignIDRow
	for rows.Next() {
		var i ListActivePlayerCharacterResistanceGlobalByCampaignIDRow
		if err := rows.Scan(
			&i.PlayerCharacterID,
			&i.DamageType,
			&i.Resistance,
			&i.Immune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlayerCharacterSpecialValuesByCampaignID = `-- name: ListActivePlayerCharacterSpecialValuesByCampaignID :many
SELECT
  pc.id AS player_character_id,
  sa.code AS special_attribute,
  pcsa.value
FROM player_characters pc
JOIN players p ON p.id = pc.player_id
JOIN player_character_special_attributes pcsa ON pcsa.player_character_id = pc.id
JOIN special_attributes sa ON sa.id = pcsa.special_attribute_id
WHERE p.campaign_id = ?1
  AND pc.active = 1
ORDER BY pc.id ASC, sa.id ASC
`

type ListActivePlayerCharacterSpecialValuesByCampaignIDRow struct {
	PlayerCharacterID string
	SpecialAttribute  string
	Value             int64
}

func (q *Queries) ListActivePlayerCharacterSpecialValuesByCampaignID(ctx context.Context, campaignID string) ([]ListActivePlayerCharacterSpecialValuesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlayerCharacterSpecialValuesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlayerCharacterSpecialValuesByCampaignIDRow
	for rows.Next() {
		var i ListActivePlayerCharacterSpecialValuesByCampaignIDRow
		if err := rows.Scan(&i.PlayerCharacterID, &i.SpecialAttribute, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBodyLocations = `-- name: ListBodyLocations :many
SELECT id, code
FROM body_locations
ORDER BY code ASC
`

func (q *Queries) ListBodyLocations(ctx context.Context) ([]BodyLocation, error) {
	rows, err := q.db.QueryContext(ctx, listBodyLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyLocation
	for rows.Next() {
		var i BodyLocation
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, start_date, party_ap, gm_threat, updated_at
FROM campaigns
ORDER BY updated_at DESC, id DESC
`

type ListCampaignsRow struct {
	ID        string
	Name      string
	StartDate time.Time
	PartyAp   int64
	GmThreat  int64
	UpdatedAt time.Time
}

func (q *Queries) ListCampaigns(ctx context.Context) ([]ListCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.PartyAp,
			&i.GmThreat,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatantIDsByEncounterID = `-- name: ListCombatantIDsByEncounterID :many
SELECT id
FROM combatants
WHERE encounter_id = ?1
`

func (q *Queries) ListCombatantIDsByEncounterID(ctx context.Context, encounterID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantIDsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatantResistanceByLocationByEncounterID = `-- name: ListCombatantResistanceByLocationByEncounterID :many
SELECT
  c.id AS combatant_id,
  dt.code AS damage_type,
  bl.code AS body_location,
  sprl.resistance
FROM combatants c
JOIN stat_profile_resistance_by_location sprl ON sprl.stat_profile_id = c.stat_profile_id
JOIN damage_types dt ON dt.id = sprl.damage_type_id
JOIN body_locations bl ON bl.id = sprl.body_location_id
WHERE c.encounter_id = ?1
  AND bl.code <> 'global'
ORDER BY c.position ASC, dt.id ASC, bl.id ASC
`

type ListCombatantResistanceByLocationByEncounterIDRow struct {
	CombatantID  string
	DamageType   string
	BodyLocation string
	Resistance   int64
}

func (q *Queries) ListCombatantResistanceByLocationByEncounterID(ctx context.Context, encounterID string) ([]ListCombatantResistanceByLocationByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantResistanceByLocationByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatantResistanceByLocationByEncounterIDRow
	for rows.Next() {
		var i ListCombatantResistanceByLocationByEncounterIDRow
		if err := rows.Scan(
			&i.CombatantID,
			&i.DamageType,
			&i.BodyLocation,
			&i.Resistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatantResistanceGlobalByEncounterID = `-- name: ListCombatantResistanceGlobalByEncounterID :many
SELECT
  c.id AS combatant_id,
  dt.code AS damage_type,
  sprg.resistance,
  sprg.immune
FROM combatants c
JOIN stat_profile_resistance_by_location sprg ON sprg.stat_profile_id = c.stat_profile_id
JOIN body_locations bl ON bl.id = sprg.body_location_id
  AND bl.code = 'global'
JOIN damage_types dt ON dt.id = sprg.damage_type_id
WHERE c.encounter_id = ?1
ORDER BY c.position ASC, dt.id ASC
`

type ListCombatantResistanceGlobalByEncounterIDRow struct {
	CombatantID string
	DamageType  string
	Resistance  int64
	Immune      int64
}

func (q *Queries) ListCombatantResistanceGlobalByEncounterID(ctx context.Context, encounterID string) ([]ListCombatantResistanceGlobalByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantResistanceGlobalByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatantResistanceGlobalByEncounterIDRow
	for rows.Next() {
		var i ListCombatantResistanceGlobalByEncounterIDRow
		if err := rows.Scan(
			&i.CombatantID,
			&i.DamageType,
			&i.Resistance,
			&i.Immune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatantsByEncounterID = `-- name: ListCombatantsByEncounterID :many
SELECT
  c.id,
  c.player_character_id,
  c.name,
  c.side,
  csp.level,
  csp.xp,
  csp.initiative,
  csp.hp,
  csp.max_hp,
  csp.defense,
  csp.torso_only,
  CAST(CASE WHEN c.position = e.turn_index THEN 1 ELSE 0 END AS INTEGER) AS active,
  c.defeated
FROM combatants c
JOIN stat_profiles csp ON csp.id = c.stat_profile_id
JOIN encounters e ON e.id = c.encounter_id
WHERE c.encounter_id = ?1
ORDER BY c.position ASC
`

type ListCombatantsByEncounterIDRow struct {
	ID                string
	PlayerCharacterID interface{}
	Name              string
	Side              string
	Level             int64
	Xp                int64
	Initiative        int64
	Hp                int64
	MaxHp             int64
	Defense           int64
	TorsoOnly         int64
	Active            int64
	Defeated          int64
}

func (q *Queries) ListCombatantsByEncounterID(ctx context.Context, encounterID string) ([]ListCombatantsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatantsByEncounterIDRow
	for rows.Next() {
		var i ListCombatantsByEncounterIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerCharacterID,
			&i.Name,
			&i.Side,
			&i.Level,
			&i.Xp,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
			&i.Active,
			&i.Defeated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDamageTypes = `-- name: ListDamageTypes :many
SELECT id, code
FROM damage_types
ORDER BY code ASC
`

func (q *Queries) ListDamageTypes(ctx context.Context) ([]DamageType, error) {
	rows, err := q.db.QueryContext(ctx, listDamageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DamageType
	for rows.Next() {
		var i DamageType
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterIDsByCampaignID = `-- name: ListEncounterIDsByCampaignID :many
SELECT id
FROM encounters
WHERE deleted_at IS NULL AND campaign_id = ?1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListEncounterIDsByCampaignID(ctx context.Context, campaignID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterIDsByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterLogsByEncounterID = `-- name: ListEncounterLogsByEncounterID :many
SELECT round, message, created_at
FROM encounter_logs
WHERE encounter_id = ?1
ORDER BY created_at DESC, rowid DESC
`

type ListEncounterLogsByEncounterIDRow struct {
	Round     int64
	Message   string
	CreatedAt time.Time
}

func (q *Queries) ListEncounterLogsByEncounterID(ctx context.Context, encounterID string) ([]ListEncounterLogsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterLogsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterLogsByEncounterIDRow
	for rows.Next() {
		var i ListEncounterLogsByEncounterIDRow
		if err := rows.Scan(&i.Round, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterSummariesByCampaignID = `-- name: ListEncounterSummariesByCampaignID :many
SELECT
  e.id,
  e.campaign_id,
  e.name,
  e.round,
  COUNT(c.id) AS combatants,
  e.updated_at
FROM encounters e
LEFT JOIN combatants c ON c.encounter_id = e.id
WHERE e.deleted_at IS NULL AND e.campaign_id = ?1
GROUP BY
  e.id, e.campaign_id, e.name, e.round, e.updated_at
ORDER BY e.updated_at DESC, e.id DESC
`

type ListEncounterSummariesByCampaignIDRow struct {
	ID         string
	CampaignID string
	Name       string
	Round      int64
	Combatants int64
	UpdatedAt  time.Time
}

func (q *Queries) ListEncounterSummariesByCampaignID(ctx context.Context, campaignID string) ([]ListEncounterSummariesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterSummariesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterSummariesByCampaignIDRow
	for rows.Next() {
		var i ListEncounterSummariesByCampaignIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Round,
			&i.Combatants,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInactiveCurrentPlayerCharacterIDsByCampaignID = `-- name: ListInactiveCurrentPlayerCharacterIDsByCampaignID :many
SELECT pc.id
FROM player_characters pc
JOIN players p ON p.id = pc.player_id
WHERE p.campaign_id = ?1
  AND pc.active = 1
  AND pc.availability_status = 'inactive'
`

func (q *Queries) ListInactiveCurrentPlayerCharacterIDsByCampaignID(ctx context.Context, campaignID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listInactiveCurrentPlayerCharacterIDsByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedCombatantsByEncounterID = `-- name: ListLinkedCombatantsByEncounterID :many
SELECT id, CAST(player_character_id AS TEXT) AS player_character_id
FROM combatants
WHERE encounter_id = ?1
  AND side = 'party'
  AND player_character_id IS NOT NULL
ORDER BY position ASC
`

type ListLinkedCombatantsByEncounterIDRow struct {
	ID                string
	PlayerCharacterID string
}

func (q *Queries) ListLinkedCombatantsByEncounterID(ctx context.Context, encounterID string) ([]ListLinkedCombatantsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedCombatantsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkedCombatantsByEncounterIDRow
	for rows.Next() {
		var i ListLinkedCombatantsByEncounterIDRow
		if err := rows.Scan(&i.ID, &i.PlayerCharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedPlayerCharacterResistanceByLocationByEncounterID = `-- name: ListLinkedPlayerCharacterResistanceByLocationByEncounterID :many
SELECT
  c.id AS combatant_id,
  pc.id AS player_character_id,
  dt.code AS damage_type,
  bl.code AS body_location,
  sprl.resistance
FROM combatants c
JOIN encounters e ON e.id = c.encounter_id
JOIN player_characters pc ON pc.id = c.player_character_id
JOIN players p ON p.id = pc.player_id
  AND p.campaign_id = e.campaign_id
JOIN stat_profile_resistance_by_location sprl ON sprl.stat_profile_id = pc.stat_profile_id
JOIN damage_types dt ON dt.id = sprl.damage_type_id
JOIN body_locations bl ON bl.id = sprl.body_location_id
WHERE c.encounter_id = ?1
  AND c.side = 'party'
  AND bl.code <> 'global'
ORDER BY c.position ASC, dt.id ASC, bl.id ASC
`

type ListLinkedPlayerCharacterResistanceByLocationByEncounterIDRow struct {
	CombatantID       string
	PlayerCharacterID string
	DamageType        string
	BodyLocation      string
	Resistance        int64
}

func (q *Queries) ListLinkedPlayerCharacterResistanceByLocationByEncounterID(ctx context.Context, encounterID string) ([]ListLinkedPlayerCharacterResistanceByLocationByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedPlayerCharacterResistanceByLocationByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkedPlayerCharacterResistanceByLocationByEncounterIDRow
	for rows.Next() {
		var i ListLinkedPlayerCharacterResistanceByLocationByEncounterIDRow
		if err := rows.Scan(
			&i.CombatantID,
			&i.PlayerCharacterID,
			&i.DamageType,
			&i.BodyLocation,
			&i.Resistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedPlayerCharacterResistanceGlobalByEncounterID = `-- name: ListLinkedPlayerCharacterResistanceGlobalByEncounterID :many
SELECT
  c.id AS combatant_id,
  pc.id AS player_character_id,
  dt.code AS damage_type,
  sprg.resistance,
  sprg.immune
FROM combatants c
JOIN encounters e ON e.id = c.encounter_id
JOIN player_characters pc ON pc.id = c.player_character_id
JOIN players p ON p.id = pc.player_id
  AND p.campaign_id = e.campaign_id
JOIN stat_profile_resistance_by_location sprg ON sprg.stat_profile_id = pc.stat_profile_id
JOIN body_locations bl ON bl.id = sprg.body_location_id
  AND bl.code = 'global'
JOIN damage_types dt ON dt.id = sprg.damage_type_id
WHERE c.encounter_id = ?1
  AND c.side = 'party'
ORDER BY c.position ASC, dt.id ASC
`

type ListLinkedPlayerCharacterResistanceGlobalByEncounterIDRow struct {
	CombatantID       string
	PlayerCharacterID string
	DamageType        string
	Resistance        int64
	Immune            int64
}

func (q *Queries) ListLinkedPlayerCharacterResistanceGlobalByEncounterID(ctx context.Context, encounterID string) ([]ListLinkedPlayerCharacterResistanceGlobalByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkedPlayerCharacterResistanceGlobalByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkedPlayerCharacterResistanceGlobalByEncounterIDRow
	for rows.Next() {
		var i ListLinkedPlayerCharacterResistanceGlobalByEncounterIDRow
		if err := rows.Scan(
			&i.CombatantID,
			&i.PlayerCharacterID,
			&i.DamageType,
			&i.Resistance,
			&i.Immune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonsterTemplateResistanceByLocation = `-- name: ListMonsterTemplateResistanceByLocation :many
SELECT
  mt.id AS monster_template_id,
  dt.code AS damage_type,
  bl.code AS body_location,
  sprl.resistance
FROM monster_templates mt
JOIN stat_profile_resistance_by_location sprl ON sprl.stat_profile_id = mt.stat_profile_id
JOIN damage_types dt ON dt.id = sprl.damage_type_id
JOIN body_locations bl ON bl.id = sprl.body_location_id
WHERE mt.deleted_at IS NULL
  AND bl.code <> 'global'
ORDER BY mt.name COLLATE NOCASE ASC, mt.id DESC, dt.id ASC, bl.id ASC
`

type ListMonsterTemplateResistanceByLocationRow struct {
	MonsterTemplateID string
	DamageType        string
	BodyLocation      string
	Resistance        int64
}

func (q *Queries) ListMonsterTemplateResistanceByLocation(ctx context.Context) ([]ListMonsterTemplateResistanceByLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonsterTemplateResistanceByLocation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonsterTemplateResistanceByLocationRow
	for rows.Next() {
		var i ListMonsterTemplateResistanceByLocationRow
		if err := rows.Scan(
			&i.MonsterTemplateID,
			&i.DamageType,
			&i.BodyLocation,
			&i.Resistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonsterTemplateResistanceGlobal = `-- name: ListMonsterTemplateResistanceGlobal :many
SELECT
  mt.id AS monster_template_id,
  dt.code AS damage_type,
  sprg.resistance,
  sprg.immune
FROM monster_templates mt
JOIN stat_profile_resistance_by_location sprg ON sprg.stat_profile_id = mt.stat_profile_id
JOIN body_locations bl ON bl.id = sprg.body_location_id
  AND bl.code = 'global'
JOIN damage_types dt ON dt.id = sprg.damage_type_id
WHERE mt.deleted_at IS NULL
ORDER BY mt.name COLLATE NOCASE ASC, mt.id DESC, dt.id ASC
`

type ListMonsterTemplateResistanceGlobalRow struct {
	MonsterTemplateID string
	DamageType        string
	Resistance        int64
	Immune            int64
}

func (q *Queries) ListMonsterTemplateResistanceGlobal(ctx context.Context) ([]ListMonsterTemplateResistanceGlobalRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonsterTemplateResistanceGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonsterTemplateResistanceGlobalRow
	for rows.Next() {
		var i ListMonsterTemplateResistanceGlobalRow
		if err := rows.Scan(
			&i.MonsterTemplateID,
			&i.DamageType,
			&i.Resistance,
			&i.Immune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonsterTemplates = `-- name: ListMonsterTemplates :many
SELECT
  mt.id,
  mt.name,
  sp.level,
  sp.xp,
  sp.initiative,
  sp.hp,
  sp.max_hp,
  sp.defense,
  sp.torso_only
FROM monster_templates mt
JOIN stat_profiles sp ON sp.id = mt.stat_profile_id
WHERE mt.deleted_at IS NULL
ORDER BY mt.name COLLATE NOCASE ASC, mt.id DESC
`

type ListMonsterTemplatesRow struct {
	ID         string
	Name       string
	Level      int64
	Xp         int64
	Initiative int64
	Hp         int64
	MaxHp      int64
	Defense    int64
	TorsoOnly  int64
}

func (q *Queries) ListMonsterTemplates(ctx context.Context) ([]ListMonsterTemplatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonsterTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonsterTemplatesRow
	for rows.Next() {
		var i ListMonsterTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Xp,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerIDsAndNamesByCampaignID = `-- name: ListPlayerIDsAndNamesByCampaignID :many
SELECT id, name
FROM players
WHERE campaign_id = ?1
`

type ListPlayerIDsAndNamesByCampaignIDRow struct {
	ID   string
	Name string
}

func (q *Queries) ListPlayerIDsAndNamesByCampaignID(ctx context.Context, campaignID string) ([]ListPlayerIDsAndNamesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerIDsAndNamesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerIDsAndNamesByCampaignIDRow
	for rows.Next() {
		var i ListPlayerIDsAndNamesByCampaignIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecialAttributes = `-- name: ListSpecialAttributes :many
SELECT id, code
FROM special_attributes
ORDER BY id ASC
`

func (q *Queries) ListSpecialAttributes(ctx context.Context) ([]SpecialAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listSpecialAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecialAttribute
	for rows.Next() {
		var i SpecialAttribute
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveCampaign = `-- name: SetActiveCampaign :execrows
UPDATE app_state
SET active_campaign_id = ?1
WHERE id = 1
  AND EXISTS (
    SELECT 1
    FROM campaigns c
    WHERE c.id = ?1
  )
`

func (q *Queries) SetActiveCampaign(ctx context.Context, campaignID interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, setActiveCampaign, campaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteEncounterByCampaign = `-- name: SoftDeleteEncounterByCampaign :execrows
UPDATE encounters
SET deleted_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE encounters.id = ?1 AND encounters.deleted_at IS NULL AND encounters.campaign_id = ?2
`

type SoftDeleteEncounterByCampaignParams struct {
	EncounterID string
	CampaignID  string
}

func (q *Queries) SoftDeleteEncounterByCampaign(ctx context.Context, arg SoftDeleteEncounterByCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncounterByCampaign, arg.EncounterID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchCampaign = `-- name: TouchCampaign :exec
UPDATE campaigns
SET updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?1
`

func (q *Queries) TouchCampaign(ctx context.Context, campaignID string) error {
	_, err := q.db.ExecContext(ctx, touchCampaign, campaignID)
	return err
}

const updateActivePlayerCharacterByID = `-- name: UpdateActivePlayerCharacterByID :exec
UPDATE player_characters
SET name = ?1,
    notes = ?2,
    active = 1,
    availability_status = ?3,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?4
`

type UpdateActivePlayerCharacterByIDParams struct {
	Name               string
	Notes              string
	AvailabilityStatus string
	CharacterID        string
}

func (q *Queries) UpdateActivePlayerCharacterByID(ctx context.Context, arg UpdateActivePlayerCharacterByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateActivePlayerCharacterByID,
		arg.Name,
		arg.Notes,
		arg.AvailabilityStatus,
		arg.CharacterID,
	)
	return err
}

const updateActivePlayerCharacterNameByID = `-- name: UpdateActivePlayerCharacterNameByID :exec
UPDATE player_characters
SET name = ?1,
    availability_status = 'active',
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?2
  AND active = 1
`

type UpdateActivePlayerCharacterNameByIDParams struct {
	Name        string
	CharacterID string
}

func (q *Queries) UpdateActivePlayerCharacterNameByID(ctx context.Context, arg UpdateActivePlayerCharacterNameByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateActivePlayerCharacterNameByID, arg.Name, arg.CharacterID)
	return err
}

const updateCampaignByID = `-- name: UpdateCampaignByID :execrows
UPDATE campaigns
SET name = ?1,
    start_date = ?2,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?3
`

type UpdateCampaignByIDParams struct {
	Name       string
	StartDate  time.Time
	CampaignID string
}

func (q *Queries) UpdateCampaignByID(ctx context.Context, arg UpdateCampaignByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCampaignByID, arg.Name, arg.StartDate, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCampaignResourcesByID = `-- name: UpdateCampaignResourcesByID :execrows
UPDATE campaigns
SET party_ap = ?1,
    gm_threat = ?2,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?3
`

type UpdateCampaignResourcesByIDParams struct {
	PartyAp    int64
	GmThreat   int64
	CampaignID string
}

func (q *Queries) UpdateCampaignResourcesByID(ctx context.Context, arg UpdateCampaignResourcesByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCampaignResourcesByID, arg.PartyAp, arg.GmThreat, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCombatantDefeatedByID = `-- name: UpdateCombatantDefeatedByID :exec
UPDATE combatants
SET defeated = ?1,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?2
`

type UpdateCombatantDefeatedByIDParams struct {
	Defeated    int64
	CombatantID string
}

func (q *Queries) UpdateCombatantDefeatedByID(ctx context.Context, arg UpdateCombatantDefeatedByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCombatantDefeatedByID, arg.Defeated, arg.CombatantID)
	return err
}

const updateLinkedCombatantSnapshotStatsByID = `-- name: UpdateLinkedCombatantSnapshotStatsByID :exec
UPDATE stat_profiles
SET level = ?1,
    hp = ?2,
    max_hp = ?3,
    defense = ?4,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE stat_profiles.id = (
  SELECT c.stat_profile_id
  FROM combatants c
  WHERE c.id = ?5
)
`

type UpdateLinkedCombatantSnapshotStatsByIDParams struct {
	Level       int64
	Hp          int64
	MaxHp       int64
	Defense     int64
	CombatantID string
}

func (q *Queries) UpdateLinkedCombatantSnapshotStatsByID(ctx context.Context, arg UpdateLinkedCombatantSnapshotStatsByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateLinkedCombatantSnapshotStatsByID,
		arg.Level,
		arg.Hp,
		arg.MaxHp,
		arg.Defense,
		arg.CombatantID,
	)
	return err
}

const upsertEncounter = `-- name: UpsertEncounter :exec
INSERT INTO encounters (
  id, campaign_id, name, round, turn_index,
  created_at, updated_at, deleted_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  NULL
)
ON CONFLICT(id) DO UPDATE SET
	campaign_id = excluded.campaign_id,
	name = excluded.name,
	round = excluded.round,
	turn_index = excluded.turn_index,
	deleted_at = NULL,
	updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertEncounterParams struct {
	ID         string
	CampaignID string
	Name       string
	Round      int64
	TurnIndex  int64
}

func (q *Queries) UpsertEncounter(ctx context.Context, arg UpsertEncounterParams) error {
	_, err := q.db.ExecContext(ctx, upsertEncounter,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.Round,
		arg.TurnIndex,
	)
	return err
}

const upsertMonsterTemplate = `-- name: UpsertMonsterTemplate :exec
INSERT INTO monster_templates (
  id, stat_profile_id, name, created_at, updated_at, deleted_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  stat_profile_id = excluded.stat_profile_id,
  name = excluded.name,
  deleted_at = NULL,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertMonsterTemplateParams struct {
	ID            string
	StatProfileID string
	Name          string
}

func (q *Queries) UpsertMonsterTemplate(ctx context.Context, arg UpsertMonsterTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonsterTemplate, arg.ID, arg.StatProfileID, arg.Name)
	return err
}

const upsertPlayerCharacterSpecialValue = `-- name: UpsertPlayerCharacterSpecialValue :exec
INSERT INTO player_character_special_attributes (
  player_character_id, special_attribute_id, value, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (player_character_id, special_attribute_id) DO UPDATE SET
  value = excluded.value,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertPlayerCharacterSpecialValueParams struct {
	PlayerCharacterID  string
	SpecialAttributeID int64
	Value              int64
}

func (q *Queries) UpsertPlayerCharacterSpecialValue(ctx context.Context, arg UpsertPlayerCharacterSpecialValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCharacterSpecialValue, arg.PlayerCharacterID, arg.SpecialAttributeID, arg.Value)
	return err
}

const upsertStatProfile = `-- name: UpsertStatProfile :exec
INSERT INTO stat_profiles (
  id, torso_only, level, xp, initiative, hp, max_hp, defense, created_at, updated_at, deleted_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  torso_only = excluded.torso_only,
  level = excluded.level,
  xp = excluded.xp,
  initiative = excluded.initiative,
  hp = excluded.hp,
  max_hp = excluded.max_hp,
  defense = excluded.defense,
  deleted_at = NULL,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertStatProfileParams struct {
	ID         string
	TorsoOnly  int64
	Level      int64
	Xp         int64
	Initiative int64
	Hp         int64
	MaxHp      int64
	Defense    int64
}

func (q *Queries) UpsertStatProfile(ctx context.Context, arg UpsertStatProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertStatProfile,
		arg.ID,
		arg.TorsoOnly,
		arg.Level,
		arg.Xp,
		arg.Initiative,
		arg.Hp,
		arg.MaxHp,
		arg.Defense,
	)
	return err
}

const upsertStatProfileResistanceByLocation = `-- name: UpsertStatProfileResistanceByLocation :exec
INSERT INTO stat_profile_resistance_by_location (
  stat_profile_id,
  damage_type_id,
  body_location_id,
  resistance,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (stat_profile_id, damage_type_id, body_location_id) DO UPDATE SET
  resistance = excluded.resistance,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertStatProfileResistanceByLocationParams struct {
	StatProfileID  string
	DamageTypeID   int64
	BodyLocationID int64
	Resistance     int64
}

func (q *Queries) UpsertStatProfileResistanceByLocation(ctx context.Context, arg UpsertStatProfileResistanceByLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertStatProfileResistanceByLocation,
		arg.StatProfileID,
		arg.DamageTypeID,
		arg.BodyLocationID,
		arg.Resistance,
	)
	return err
}

const upsertStatProfileResistanceGlobal = `-- name: UpsertStatProfileResistanceGlobal :exec
INSERT INTO stat_profile_resistance_by_location (
  stat_profile_id,
  damage_type_id,
  body_location_id,
  resistance,
  immune,
  updated_at
)
VALUES (
  ?1,
  ?2,
  (SELECT id FROM body_locations WHERE code = 'global'),
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (stat_profile_id, damage_type_id, body_location_id) DO UPDATE SET
  resistance = excluded.resistance,
  immune = excluded.immune,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertStatProfileResistanceGlobalParams struct {
	StatProfileID string
	DamageTypeID  int64
	Resistance    int64
	Immune        int64
}

func (q *Queries) UpsertStatProfileResistanceGlobal(ctx context.Context, arg UpsertStatProfileResistanceGlobalParams) error {
	_, err := q.db.ExecContext(ctx, upsertStatProfileResistanceGlobal,
		arg.StatProfileID,
		arg.DamageTypeID,
		arg.Resistance,
		arg.Immune,
	)
	return err
}
