// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"
)

const activateEncounterByCampaign = `-- name: ActivateEncounterByCampaign :execrows
UPDATE encounters
SET updated_at = CASE
  WHEN STRFTIME('%Y-%m-%d %H:%M:%f', 'now') <= COALESCE((SELECT MAX(e2.updated_at) FROM encounters e2 WHERE e2.deleted_at IS NULL AND e2.campaign_id = ?1), '')
    THEN STRFTIME(
      '%Y-%m-%d %H:%M:%f',
      COALESCE((SELECT MAX(e3.updated_at) FROM encounters e3 WHERE e3.deleted_at IS NULL AND e3.campaign_id = ?1), STRFTIME('%Y-%m-%d %H:%M:%f', 'now')),
      '+0.001 seconds'
    )
  ELSE STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
END
WHERE encounters.id = ?2 AND encounters.deleted_at IS NULL AND encounters.campaign_id = ?1
`

type ActivateEncounterByCampaignParams struct {
	CampaignID  interface{}
	EncounterID string
}

func (q *Queries) ActivateEncounterByCampaign(ctx context.Context, arg ActivateEncounterByCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateEncounterByCampaign, arg.CampaignID, arg.EncounterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deactivateActiveCharactersByPlayerID = `-- name: DeactivateActiveCharactersByPlayerID :exec
UPDATE player_characters
SET active = 0,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE player_id = ?1
  AND active = 1
`

func (q *Queries) DeactivateActiveCharactersByPlayerID(ctx context.Context, playerID string) error {
	_, err := q.db.ExecContext(ctx, deactivateActiveCharactersByPlayerID, playerID)
	return err
}

const deleteCombatantsByEncounterID = `-- name: DeleteCombatantsByEncounterID :exec
DELETE FROM combatants
WHERE encounter_id = ?1
`

func (q *Queries) DeleteCombatantsByEncounterID(ctx context.Context, encounterID string) error {
	_, err := q.db.ExecContext(ctx, deleteCombatantsByEncounterID, encounterID)
	return err
}

const deletePlayersByCampaignID = `-- name: DeletePlayersByCampaignID :exec
DELETE FROM players
WHERE campaign_id = ?1
`

func (q *Queries) DeletePlayersByCampaignID(ctx context.Context, campaignID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayersByCampaignID, campaignID)
	return err
}

const ensureAppStateRow = `-- name: EnsureAppStateRow :exec
INSERT OR IGNORE INTO app_state (id, active_campaign_id)
VALUES (1, NULL)
`

func (q *Queries) EnsureAppStateRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureAppStateRow)
	return err
}

const getActiveCampaign = `-- name: GetActiveCampaign :one
SELECT c.id, c.name, c.start_date, c.updated_at
FROM campaigns c
JOIN app_state s ON s.id = 1
WHERE c.id = s.active_campaign_id
`

type GetActiveCampaignRow struct {
	ID        string
	Name      string
	StartDate string
	UpdatedAt time.Time
}

func (q *Queries) GetActiveCampaign(ctx context.Context) (GetActiveCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCampaign)
	var i GetActiveCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePlayerCharacterByPlayerID = `-- name: GetActivePlayerCharacterByPlayerID :one
SELECT id, name
FROM player_characters
WHERE player_id = ?1
  AND active = 1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetActivePlayerCharacterByPlayerIDRow struct {
	ID   string
	Name string
}

func (q *Queries) GetActivePlayerCharacterByPlayerID(ctx context.Context, playerID string) (GetActivePlayerCharacterByPlayerIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePlayerCharacterByPlayerID, playerID)
	var i GetActivePlayerCharacterByPlayerIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, start_date, updated_at
FROM campaigns
WHERE id = ?1
`

type GetCampaignByIDRow struct {
	ID        string
	Name      string
	StartDate string
	UpdatedAt time.Time
}

func (q *Queries) GetCampaignByID(ctx context.Context, campaignID string) (GetCampaignByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, campaignID)
	var i GetCampaignByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.UpdatedAt,
	)
	return i, err
}

const getEncounterByIDByCampaignID = `-- name: GetEncounterByIDByCampaignID :one
SELECT id, campaign_id, name, round, turn_index, party_ap, gm_threat,
       difficulty_label, difficulty_score,
       party_count, party_avg_level, party_xp_budget,
       enemy_count, enemy_avg_level, enemy_total_xp
FROM encounters
WHERE deleted_at IS NULL
  AND campaign_id = ?1
  AND id = ?2
`

type GetEncounterByIDByCampaignIDParams struct {
	CampaignID  interface{}
	EncounterID string
}

type GetEncounterByIDByCampaignIDRow struct {
	ID              string
	CampaignID      interface{}
	Name            string
	Round           int64
	TurnIndex       int64
	PartyAp         int64
	GmThreat        int64
	DifficultyLabel string
	DifficultyScore float64
	PartyCount      int64
	PartyAvgLevel   float64
	PartyXpBudget   int64
	EnemyCount      int64
	EnemyAvgLevel   float64
	EnemyTotalXp    int64
}

func (q *Queries) GetEncounterByIDByCampaignID(ctx context.Context, arg GetEncounterByIDByCampaignIDParams) (GetEncounterByIDByCampaignIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEncounterByIDByCampaignID, arg.CampaignID, arg.EncounterID)
	var i GetEncounterByIDByCampaignIDRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Round,
		&i.TurnIndex,
		&i.PartyAp,
		&i.GmThreat,
		&i.DifficultyLabel,
		&i.DifficultyScore,
		&i.PartyCount,
		&i.PartyAvgLevel,
		&i.PartyXpBudget,
		&i.EnemyCount,
		&i.EnemyAvgLevel,
		&i.EnemyTotalXp,
	)
	return i, err
}

const getLatestEncounterByCampaignID = `-- name: GetLatestEncounterByCampaignID :one
SELECT id, campaign_id, name, round, turn_index, party_ap, gm_threat,
       difficulty_label, difficulty_score,
       party_count, party_avg_level, party_xp_budget,
       enemy_count, enemy_avg_level, enemy_total_xp
FROM encounters
WHERE deleted_at IS NULL AND campaign_id = ?1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetLatestEncounterByCampaignIDRow struct {
	ID              string
	CampaignID      interface{}
	Name            string
	Round           int64
	TurnIndex       int64
	PartyAp         int64
	GmThreat        int64
	DifficultyLabel string
	DifficultyScore float64
	PartyCount      int64
	PartyAvgLevel   float64
	PartyXpBudget   int64
	EnemyCount      int64
	EnemyAvgLevel   float64
	EnemyTotalXp    int64
}

func (q *Queries) GetLatestEncounterByCampaignID(ctx context.Context, campaignID interface{}) (GetLatestEncounterByCampaignIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestEncounterByCampaignID, campaignID)
	var i GetLatestEncounterByCampaignIDRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Round,
		&i.TurnIndex,
		&i.PartyAp,
		&i.GmThreat,
		&i.DifficultyLabel,
		&i.DifficultyScore,
		&i.PartyCount,
		&i.PartyAvgLevel,
		&i.PartyXpBudget,
		&i.EnemyCount,
		&i.EnemyAvgLevel,
		&i.EnemyTotalXp,
	)
	return i, err
}

const insertCampaign = `-- name: InsertCampaign :exec
INSERT INTO campaigns (id, name, start_date, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertCampaignParams struct {
	ID        string
	Name      string
	StartDate string
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) error {
	_, err := q.db.ExecContext(ctx, insertCampaign, arg.ID, arg.Name, arg.StartDate)
	return err
}

const insertCombatant = `-- name: InsertCombatant :exec
INSERT INTO combatants (
	id, encounter_id, name, side, torso_only, level, xp, initiative, hp, max_hp, defense, active, defeated, position, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
	  ?8,
	  ?9,
	  ?10,
	  ?11,
	  ?12,
	  ?13,
	  ?14,
	  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
	  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
	)
`

type InsertCombatantParams struct {
	ID          string
	EncounterID string
	Name        string
	Side        string
	TorsoOnly   int64
	Level       int64
	Xp          int64
	Initiative  int64
	Hp          int64
	MaxHp       int64
	Defense     int64
	Active      int64
	Defeated    int64
	Position    int64
}

func (q *Queries) InsertCombatant(ctx context.Context, arg InsertCombatantParams) error {
	_, err := q.db.ExecContext(ctx, insertCombatant,
		arg.ID,
		arg.EncounterID,
		arg.Name,
		arg.Side,
		arg.TorsoOnly,
		arg.Level,
		arg.Xp,
		arg.Initiative,
		arg.Hp,
		arg.MaxHp,
		arg.Defense,
		arg.Active,
		arg.Defeated,
		arg.Position,
	)
	return err
}

const insertEncounterLog = `-- name: InsertEncounterLog :exec
INSERT INTO encounter_logs (id, encounter_id, round, message, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertEncounterLogParams struct {
	ID          string
	EncounterID string
	Round       int64
	Message     string
}

func (q *Queries) InsertEncounterLog(ctx context.Context, arg InsertEncounterLogParams) error {
	_, err := q.db.ExecContext(ctx, insertEncounterLog,
		arg.ID,
		arg.EncounterID,
		arg.Round,
		arg.Message,
	)
	return err
}

const insertPlayer = `-- name: InsertPlayer :exec
INSERT INTO players (id, campaign_id, name, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertPlayerParams struct {
	ID         string
	CampaignID string
	Name       string
}

func (q *Queries) InsertPlayer(ctx context.Context, arg InsertPlayerParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayer, arg.ID, arg.CampaignID, arg.Name)
	return err
}

const insertPlayerCharacter = `-- name: InsertPlayerCharacter :exec
INSERT INTO player_characters (
  id, player_id, campaign_id, name, level, initiative, hp, max_hp, defense, torso_only, active, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertPlayerCharacterParams struct {
	ID         string
	PlayerID   string
	CampaignID string
	Name       string
	Level      int64
	Initiative int64
	Hp         int64
	MaxHp      int64
	Defense    int64
	TorsoOnly  int64
	Active     int64
}

func (q *Queries) InsertPlayerCharacter(ctx context.Context, arg InsertPlayerCharacterParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerCharacter,
		arg.ID,
		arg.PlayerID,
		arg.CampaignID,
		arg.Name,
		arg.Level,
		arg.Initiative,
		arg.Hp,
		arg.MaxHp,
		arg.Defense,
		arg.TorsoOnly,
		arg.Active,
	)
	return err
}

const listActivePartyCharactersByCampaignID = `-- name: ListActivePartyCharactersByCampaignID :many
WITH player_character_defense AS (
  SELECT
    cdl.player_character_id,
    MAX(CASE WHEN bl.code = 'head' THEN cdl.defense END) AS defense_head,
    MAX(CASE WHEN bl.code = 'torso' THEN cdl.defense END) AS defense_torso,
    MAX(CASE WHEN bl.code = 'left_arm' THEN cdl.defense END) AS defense_left_arm,
    MAX(CASE WHEN bl.code = 'right_arm' THEN cdl.defense END) AS defense_right_arm,
    MAX(CASE WHEN bl.code = 'left_leg' THEN cdl.defense END) AS defense_left_leg,
    MAX(CASE WHEN bl.code = 'right_leg' THEN cdl.defense END) AS defense_right_leg
  FROM player_character_defense_by_location cdl
  JOIN body_locations bl ON bl.id = cdl.body_location_id
  GROUP BY cdl.player_character_id
),
player_character_resistance_global_agg AS (
  SELECT
    crg.player_character_id,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.resistance END) AS damage_resistance_physical,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.resistance END) AS damage_resistance_energy,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.resistance END) AS damage_resistance_radiation,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.resistance END) AS damage_resistance_poison,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.immune END) AS damage_resistance_physical_immune,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.immune END) AS damage_resistance_energy_immune,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.immune END) AS damage_resistance_radiation_immune,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.immune END) AS damage_resistance_poison_immune
  FROM player_character_resistance_global crg
  JOIN damage_types dt ON dt.id = crg.damage_type_id
  GROUP BY crg.player_character_id
),
player_character_resistance_by_location_agg AS (
  SELECT
    crl.player_character_id,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_physical_head,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_physical_torso,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_physical_left_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_physical_right_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_physical_left_leg,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_physical_right_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_energy_head,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_energy_torso,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_energy_left_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_energy_right_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_energy_left_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_energy_right_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_radiation_head,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_radiation_torso,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_radiation_left_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_radiation_right_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_radiation_left_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_radiation_right_leg
  FROM player_character_resistance_by_location crl
  JOIN damage_types dt ON dt.id = crl.damage_type_id
  JOIN body_locations bl ON bl.id = crl.body_location_id
  GROUP BY crl.player_character_id
)
SELECT
  pc.id,
  p.name AS player_name,
  pc.name AS character_name,
  pc.level,
  pc.initiative,
  pc.hp,
  pc.max_hp,
  pc.defense,
  pc.torso_only,
  CAST(COALESCE(cdl.defense_head, 0) AS INTEGER) AS defense_head,
  CAST(COALESCE(cdl.defense_torso, 0) AS INTEGER) AS defense_torso,
  CAST(COALESCE(cdl.defense_left_arm, 0) AS INTEGER) AS defense_left_arm,
  CAST(COALESCE(cdl.defense_right_arm, 0) AS INTEGER) AS defense_right_arm,
  CAST(COALESCE(cdl.defense_left_leg, 0) AS INTEGER) AS defense_left_leg,
  CAST(COALESCE(cdl.defense_right_leg, 0) AS INTEGER) AS defense_right_leg,
  CAST(COALESCE(crl.damage_resistance_physical_head, 0) AS INTEGER) AS damage_resistance_physical_head,
  CAST(COALESCE(crl.damage_resistance_physical_torso, 0) AS INTEGER) AS damage_resistance_physical_torso,
  CAST(COALESCE(crl.damage_resistance_physical_left_arm, 0) AS INTEGER) AS damage_resistance_physical_left_arm,
  CAST(COALESCE(crl.damage_resistance_physical_right_arm, 0) AS INTEGER) AS damage_resistance_physical_right_arm,
  CAST(COALESCE(crl.damage_resistance_physical_left_leg, 0) AS INTEGER) AS damage_resistance_physical_left_leg,
  CAST(COALESCE(crl.damage_resistance_physical_right_leg, 0) AS INTEGER) AS damage_resistance_physical_right_leg,
  CAST(COALESCE(crg.damage_resistance_physical, 0) AS INTEGER) AS damage_resistance_physical,
  CAST(COALESCE(crg.damage_resistance_energy, 0) AS INTEGER) AS damage_resistance_energy,
  CAST(COALESCE(crg.damage_resistance_radiation, 0) AS INTEGER) AS damage_resistance_radiation,
  CAST(COALESCE(crg.damage_resistance_poison, 0) AS INTEGER) AS damage_resistance_poison,
  CAST(COALESCE(crl.damage_resistance_energy_head, 0) AS INTEGER) AS damage_resistance_energy_head,
  CAST(COALESCE(crl.damage_resistance_energy_torso, 0) AS INTEGER) AS damage_resistance_energy_torso,
  CAST(COALESCE(crl.damage_resistance_energy_left_arm, 0) AS INTEGER) AS damage_resistance_energy_left_arm,
  CAST(COALESCE(crl.damage_resistance_energy_right_arm, 0) AS INTEGER) AS damage_resistance_energy_right_arm,
  CAST(COALESCE(crl.damage_resistance_energy_left_leg, 0) AS INTEGER) AS damage_resistance_energy_left_leg,
  CAST(COALESCE(crl.damage_resistance_energy_right_leg, 0) AS INTEGER) AS damage_resistance_energy_right_leg,
  CAST(COALESCE(crl.damage_resistance_radiation_head, 0) AS INTEGER) AS damage_resistance_radiation_head,
  CAST(COALESCE(crl.damage_resistance_radiation_torso, 0) AS INTEGER) AS damage_resistance_radiation_torso,
  CAST(COALESCE(crl.damage_resistance_radiation_left_arm, 0) AS INTEGER) AS damage_resistance_radiation_left_arm,
  CAST(COALESCE(crl.damage_resistance_radiation_right_arm, 0) AS INTEGER) AS damage_resistance_radiation_right_arm,
  CAST(COALESCE(crl.damage_resistance_radiation_left_leg, 0) AS INTEGER) AS damage_resistance_radiation_left_leg,
  CAST(COALESCE(crl.damage_resistance_radiation_right_leg, 0) AS INTEGER) AS damage_resistance_radiation_right_leg,
  CAST(COALESCE(crg.damage_resistance_physical_immune, 0) AS INTEGER) AS damage_resistance_physical_immune,
  CAST(COALESCE(crg.damage_resistance_energy_immune, 0) AS INTEGER) AS damage_resistance_energy_immune,
  CAST(COALESCE(crg.damage_resistance_radiation_immune, 0) AS INTEGER) AS damage_resistance_radiation_immune,
  CAST(COALESCE(crg.damage_resistance_poison_immune, 0) AS INTEGER) AS damage_resistance_poison_immune
FROM player_characters pc
JOIN players p ON p.id = pc.player_id
LEFT JOIN player_character_defense cdl ON cdl.player_character_id = pc.id
LEFT JOIN player_character_resistance_global_agg crg ON crg.player_character_id = pc.id
LEFT JOIN player_character_resistance_by_location_agg crl ON crl.player_character_id = pc.id
WHERE pc.campaign_id = ?1 AND pc.active = 1
ORDER BY p.name COLLATE NOCASE ASC, pc.name COLLATE NOCASE ASC
`

type ListActivePartyCharactersByCampaignIDRow struct {
	ID                                string
	PlayerName                        string
	CharacterName                     string
	Level                             int64
	Initiative                        int64
	Hp                                int64
	MaxHp                             int64
	Defense                           int64
	TorsoOnly                         int64
	DefenseHead                       int64
	DefenseTorso                      int64
	DefenseLeftArm                    int64
	DefenseRightArm                   int64
	DefenseLeftLeg                    int64
	DefenseRightLeg                   int64
	DamageResistancePhysicalHead      int64
	DamageResistancePhysicalTorso     int64
	DamageResistancePhysicalLeftArm   int64
	DamageResistancePhysicalRightArm  int64
	DamageResistancePhysicalLeftLeg   int64
	DamageResistancePhysicalRightLeg  int64
	DamageResistancePhysical          int64
	DamageResistanceEnergy            int64
	DamageResistanceRadiation         int64
	DamageResistancePoison            int64
	DamageResistanceEnergyHead        int64
	DamageResistanceEnergyTorso       int64
	DamageResistanceEnergyLeftArm     int64
	DamageResistanceEnergyRightArm    int64
	DamageResistanceEnergyLeftLeg     int64
	DamageResistanceEnergyRightLeg    int64
	DamageResistanceRadiationHead     int64
	DamageResistanceRadiationTorso    int64
	DamageResistanceRadiationLeftArm  int64
	DamageResistanceRadiationRightArm int64
	DamageResistanceRadiationLeftLeg  int64
	DamageResistanceRadiationRightLeg int64
	DamageResistancePhysicalImmune    int64
	DamageResistanceEnergyImmune      int64
	DamageResistanceRadiationImmune   int64
	DamageResistancePoisonImmune      int64
}

func (q *Queries) ListActivePartyCharactersByCampaignID(ctx context.Context, campaignID string) ([]ListActivePartyCharactersByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePartyCharactersByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePartyCharactersByCampaignIDRow
	for rows.Next() {
		var i ListActivePartyCharactersByCampaignIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.CharacterName,
			&i.Level,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
			&i.DefenseHead,
			&i.DefenseTorso,
			&i.DefenseLeftArm,
			&i.DefenseRightArm,
			&i.DefenseLeftLeg,
			&i.DefenseRightLeg,
			&i.DamageResistancePhysicalHead,
			&i.DamageResistancePhysicalTorso,
			&i.DamageResistancePhysicalLeftArm,
			&i.DamageResistancePhysicalRightArm,
			&i.DamageResistancePhysicalLeftLeg,
			&i.DamageResistancePhysicalRightLeg,
			&i.DamageResistancePhysical,
			&i.DamageResistanceEnergy,
			&i.DamageResistanceRadiation,
			&i.DamageResistancePoison,
			&i.DamageResistanceEnergyHead,
			&i.DamageResistanceEnergyTorso,
			&i.DamageResistanceEnergyLeftArm,
			&i.DamageResistanceEnergyRightArm,
			&i.DamageResistanceEnergyLeftLeg,
			&i.DamageResistanceEnergyRightLeg,
			&i.DamageResistanceRadiationHead,
			&i.DamageResistanceRadiationTorso,
			&i.DamageResistanceRadiationLeftArm,
			&i.DamageResistanceRadiationRightArm,
			&i.DamageResistanceRadiationLeftLeg,
			&i.DamageResistanceRadiationRightLeg,
			&i.DamageResistancePhysicalImmune,
			&i.DamageResistanceEnergyImmune,
			&i.DamageResistanceRadiationImmune,
			&i.DamageResistancePoisonImmune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, start_date, updated_at
FROM campaigns
ORDER BY updated_at DESC, id DESC
`

type ListCampaignsRow struct {
	ID        string
	Name      string
	StartDate string
	UpdatedAt time.Time
}

func (q *Queries) ListCampaigns(ctx context.Context) ([]ListCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatantsByEncounterID = `-- name: ListCombatantsByEncounterID :many
WITH combatant_defense AS (
  SELECT
    cdl.combatant_id,
    MAX(CASE WHEN bl.code = 'head' THEN cdl.defense END) AS defense_head,
    MAX(CASE WHEN bl.code = 'torso' THEN cdl.defense END) AS defense_torso,
    MAX(CASE WHEN bl.code = 'left_arm' THEN cdl.defense END) AS defense_left_arm,
    MAX(CASE WHEN bl.code = 'right_arm' THEN cdl.defense END) AS defense_right_arm,
    MAX(CASE WHEN bl.code = 'left_leg' THEN cdl.defense END) AS defense_left_leg,
    MAX(CASE WHEN bl.code = 'right_leg' THEN cdl.defense END) AS defense_right_leg
  FROM combatant_defense_by_location cdl
  JOIN body_locations bl ON bl.id = cdl.body_location_id
  GROUP BY cdl.combatant_id
),
combatant_resistance_global_agg AS (
  SELECT
    crg.combatant_id,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.resistance END) AS damage_resistance_physical,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.resistance END) AS damage_resistance_energy,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.resistance END) AS damage_resistance_radiation,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.resistance END) AS damage_resistance_poison,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.immune END) AS damage_resistance_physical_immune,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.immune END) AS damage_resistance_energy_immune,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.immune END) AS damage_resistance_radiation_immune,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.immune END) AS damage_resistance_poison_immune
  FROM combatant_resistance_global crg
  JOIN damage_types dt ON dt.id = crg.damage_type_id
  GROUP BY crg.combatant_id
),
combatant_resistance_by_location_agg AS (
  SELECT
    crl.combatant_id,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_physical_head,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_physical_torso,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_physical_left_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_physical_right_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_physical_left_leg,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_physical_right_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_energy_head,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_energy_torso,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_energy_left_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_energy_right_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_energy_left_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_energy_right_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_radiation_head,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_radiation_torso,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_radiation_left_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_radiation_right_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_radiation_left_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_radiation_right_leg
  FROM combatant_resistance_by_location crl
  JOIN damage_types dt ON dt.id = crl.damage_type_id
  JOIN body_locations bl ON bl.id = crl.body_location_id
  GROUP BY crl.combatant_id
)
SELECT
  c.id,
  c.name,
  c.side,
  c.level,
  c.xp,
  c.initiative,
  c.hp,
  c.max_hp,
  c.defense,
  c.torso_only,
  CAST(COALESCE(cdl.defense_head, 0) AS INTEGER) AS defense_head,
  CAST(COALESCE(cdl.defense_torso, 0) AS INTEGER) AS defense_torso,
  CAST(COALESCE(cdl.defense_left_arm, 0) AS INTEGER) AS defense_left_arm,
  CAST(COALESCE(cdl.defense_right_arm, 0) AS INTEGER) AS defense_right_arm,
  CAST(COALESCE(cdl.defense_left_leg, 0) AS INTEGER) AS defense_left_leg,
  CAST(COALESCE(cdl.defense_right_leg, 0) AS INTEGER) AS defense_right_leg,
  CAST(COALESCE(crl.damage_resistance_physical_head, 0) AS INTEGER) AS damage_resistance_physical_head,
  CAST(COALESCE(crl.damage_resistance_physical_torso, 0) AS INTEGER) AS damage_resistance_physical_torso,
  CAST(COALESCE(crl.damage_resistance_physical_left_arm, 0) AS INTEGER) AS damage_resistance_physical_left_arm,
  CAST(COALESCE(crl.damage_resistance_physical_right_arm, 0) AS INTEGER) AS damage_resistance_physical_right_arm,
  CAST(COALESCE(crl.damage_resistance_physical_left_leg, 0) AS INTEGER) AS damage_resistance_physical_left_leg,
  CAST(COALESCE(crl.damage_resistance_physical_right_leg, 0) AS INTEGER) AS damage_resistance_physical_right_leg,
  CAST(COALESCE(crg.damage_resistance_physical, 0) AS INTEGER) AS damage_resistance_physical,
  CAST(COALESCE(crg.damage_resistance_energy, 0) AS INTEGER) AS damage_resistance_energy,
  CAST(COALESCE(crg.damage_resistance_radiation, 0) AS INTEGER) AS damage_resistance_radiation,
  CAST(COALESCE(crg.damage_resistance_poison, 0) AS INTEGER) AS damage_resistance_poison,
  CAST(COALESCE(crl.damage_resistance_energy_head, 0) AS INTEGER) AS damage_resistance_energy_head,
  CAST(COALESCE(crl.damage_resistance_energy_torso, 0) AS INTEGER) AS damage_resistance_energy_torso,
  CAST(COALESCE(crl.damage_resistance_energy_left_arm, 0) AS INTEGER) AS damage_resistance_energy_left_arm,
  CAST(COALESCE(crl.damage_resistance_energy_right_arm, 0) AS INTEGER) AS damage_resistance_energy_right_arm,
  CAST(COALESCE(crl.damage_resistance_energy_left_leg, 0) AS INTEGER) AS damage_resistance_energy_left_leg,
  CAST(COALESCE(crl.damage_resistance_energy_right_leg, 0) AS INTEGER) AS damage_resistance_energy_right_leg,
  CAST(COALESCE(crl.damage_resistance_radiation_head, 0) AS INTEGER) AS damage_resistance_radiation_head,
  CAST(COALESCE(crl.damage_resistance_radiation_torso, 0) AS INTEGER) AS damage_resistance_radiation_torso,
  CAST(COALESCE(crl.damage_resistance_radiation_left_arm, 0) AS INTEGER) AS damage_resistance_radiation_left_arm,
  CAST(COALESCE(crl.damage_resistance_radiation_right_arm, 0) AS INTEGER) AS damage_resistance_radiation_right_arm,
  CAST(COALESCE(crl.damage_resistance_radiation_left_leg, 0) AS INTEGER) AS damage_resistance_radiation_left_leg,
  CAST(COALESCE(crl.damage_resistance_radiation_right_leg, 0) AS INTEGER) AS damage_resistance_radiation_right_leg,
  CAST(COALESCE(crg.damage_resistance_physical_immune, 0) AS INTEGER) AS damage_resistance_physical_immune,
  CAST(COALESCE(crg.damage_resistance_energy_immune, 0) AS INTEGER) AS damage_resistance_energy_immune,
  CAST(COALESCE(crg.damage_resistance_radiation_immune, 0) AS INTEGER) AS damage_resistance_radiation_immune,
  CAST(COALESCE(crg.damage_resistance_poison_immune, 0) AS INTEGER) AS damage_resistance_poison_immune,
  c.active,
  c.defeated
FROM combatants c
LEFT JOIN combatant_defense cdl ON cdl.combatant_id = c.id
LEFT JOIN combatant_resistance_global_agg crg ON crg.combatant_id = c.id
LEFT JOIN combatant_resistance_by_location_agg crl ON crl.combatant_id = c.id
WHERE c.encounter_id = ?1
ORDER BY c.position ASC
`

type ListCombatantsByEncounterIDRow struct {
	ID                                string
	Name                              string
	Side                              string
	Level                             int64
	Xp                                int64
	Initiative                        int64
	Hp                                int64
	MaxHp                             int64
	Defense                           int64
	TorsoOnly                         int64
	DefenseHead                       int64
	DefenseTorso                      int64
	DefenseLeftArm                    int64
	DefenseRightArm                   int64
	DefenseLeftLeg                    int64
	DefenseRightLeg                   int64
	DamageResistancePhysicalHead      int64
	DamageResistancePhysicalTorso     int64
	DamageResistancePhysicalLeftArm   int64
	DamageResistancePhysicalRightArm  int64
	DamageResistancePhysicalLeftLeg   int64
	DamageResistancePhysicalRightLeg  int64
	DamageResistancePhysical          int64
	DamageResistanceEnergy            int64
	DamageResistanceRadiation         int64
	DamageResistancePoison            int64
	DamageResistanceEnergyHead        int64
	DamageResistanceEnergyTorso       int64
	DamageResistanceEnergyLeftArm     int64
	DamageResistanceEnergyRightArm    int64
	DamageResistanceEnergyLeftLeg     int64
	DamageResistanceEnergyRightLeg    int64
	DamageResistanceRadiationHead     int64
	DamageResistanceRadiationTorso    int64
	DamageResistanceRadiationLeftArm  int64
	DamageResistanceRadiationRightArm int64
	DamageResistanceRadiationLeftLeg  int64
	DamageResistanceRadiationRightLeg int64
	DamageResistancePhysicalImmune    int64
	DamageResistanceEnergyImmune      int64
	DamageResistanceRadiationImmune   int64
	DamageResistancePoisonImmune      int64
	Active                            int64
	Defeated                          int64
}

func (q *Queries) ListCombatantsByEncounterID(ctx context.Context, encounterID string) ([]ListCombatantsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatantsByEncounterIDRow
	for rows.Next() {
		var i ListCombatantsByEncounterIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Side,
			&i.Level,
			&i.Xp,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
			&i.DefenseHead,
			&i.DefenseTorso,
			&i.DefenseLeftArm,
			&i.DefenseRightArm,
			&i.DefenseLeftLeg,
			&i.DefenseRightLeg,
			&i.DamageResistancePhysicalHead,
			&i.DamageResistancePhysicalTorso,
			&i.DamageResistancePhysicalLeftArm,
			&i.DamageResistancePhysicalRightArm,
			&i.DamageResistancePhysicalLeftLeg,
			&i.DamageResistancePhysicalRightLeg,
			&i.DamageResistancePhysical,
			&i.DamageResistanceEnergy,
			&i.DamageResistanceRadiation,
			&i.DamageResistancePoison,
			&i.DamageResistanceEnergyHead,
			&i.DamageResistanceEnergyTorso,
			&i.DamageResistanceEnergyLeftArm,
			&i.DamageResistanceEnergyRightArm,
			&i.DamageResistanceEnergyLeftLeg,
			&i.DamageResistanceEnergyRightLeg,
			&i.DamageResistanceRadiationHead,
			&i.DamageResistanceRadiationTorso,
			&i.DamageResistanceRadiationLeftArm,
			&i.DamageResistanceRadiationRightArm,
			&i.DamageResistanceRadiationLeftLeg,
			&i.DamageResistanceRadiationRightLeg,
			&i.DamageResistancePhysicalImmune,
			&i.DamageResistanceEnergyImmune,
			&i.DamageResistanceRadiationImmune,
			&i.DamageResistancePoisonImmune,
			&i.Active,
			&i.Defeated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterLogsByEncounterID = `-- name: ListEncounterLogsByEncounterID :many
SELECT round, message, created_at
FROM encounter_logs
WHERE encounter_id = ?1
ORDER BY created_at DESC, rowid DESC
`

type ListEncounterLogsByEncounterIDRow struct {
	Round     int64
	Message   string
	CreatedAt time.Time
}

func (q *Queries) ListEncounterLogsByEncounterID(ctx context.Context, encounterID string) ([]ListEncounterLogsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterLogsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterLogsByEncounterIDRow
	for rows.Next() {
		var i ListEncounterLogsByEncounterIDRow
		if err := rows.Scan(&i.Round, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterPartyTemplatesByCampaignID = `-- name: ListEncounterPartyTemplatesByCampaignID :many
WITH combatant_defense AS (
  SELECT
    cdl.combatant_id,
    MAX(CASE WHEN bl.code = 'head' THEN cdl.defense END) AS defense_head,
    MAX(CASE WHEN bl.code = 'torso' THEN cdl.defense END) AS defense_torso,
    MAX(CASE WHEN bl.code = 'left_arm' THEN cdl.defense END) AS defense_left_arm,
    MAX(CASE WHEN bl.code = 'right_arm' THEN cdl.defense END) AS defense_right_arm,
    MAX(CASE WHEN bl.code = 'left_leg' THEN cdl.defense END) AS defense_left_leg,
    MAX(CASE WHEN bl.code = 'right_leg' THEN cdl.defense END) AS defense_right_leg
  FROM combatant_defense_by_location cdl
  JOIN body_locations bl ON bl.id = cdl.body_location_id
  GROUP BY cdl.combatant_id
),
combatant_resistance_global_agg AS (
  SELECT
    crg.combatant_id,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.resistance END) AS damage_resistance_physical,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.resistance END) AS damage_resistance_energy,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.resistance END) AS damage_resistance_radiation,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.resistance END) AS damage_resistance_poison,
    MAX(CASE WHEN dt.code = 'physical' THEN crg.immune END) AS damage_resistance_physical_immune,
    MAX(CASE WHEN dt.code = 'energy' THEN crg.immune END) AS damage_resistance_energy_immune,
    MAX(CASE WHEN dt.code = 'radiation' THEN crg.immune END) AS damage_resistance_radiation_immune,
    MAX(CASE WHEN dt.code = 'poison' THEN crg.immune END) AS damage_resistance_poison_immune
  FROM combatant_resistance_global crg
  JOIN damage_types dt ON dt.id = crg.damage_type_id
  GROUP BY crg.combatant_id
),
combatant_resistance_by_location_agg AS (
  SELECT
    crl.combatant_id,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_physical_head,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_physical_torso,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_physical_left_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_physical_right_arm,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_physical_left_leg,
    MAX(CASE WHEN dt.code = 'physical' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_physical_right_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_energy_head,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_energy_torso,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_energy_left_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_energy_right_arm,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_energy_left_leg,
    MAX(CASE WHEN dt.code = 'energy' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_energy_right_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'head' THEN crl.resistance END) AS damage_resistance_radiation_head,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'torso' THEN crl.resistance END) AS damage_resistance_radiation_torso,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_arm' THEN crl.resistance END) AS damage_resistance_radiation_left_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_arm' THEN crl.resistance END) AS damage_resistance_radiation_right_arm,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'left_leg' THEN crl.resistance END) AS damage_resistance_radiation_left_leg,
    MAX(CASE WHEN dt.code = 'radiation' AND bl.code = 'right_leg' THEN crl.resistance END) AS damage_resistance_radiation_right_leg
  FROM combatant_resistance_by_location crl
  JOIN damage_types dt ON dt.id = crl.damage_type_id
  JOIN body_locations bl ON bl.id = crl.body_location_id
  GROUP BY crl.combatant_id
),
latest_party AS (
  SELECT
    c.name,
    c.level,
    c.xp,
    c.initiative,
    c.hp,
    c.max_hp,
    c.defense,
    c.torso_only,
    CAST(COALESCE(cdl.defense_head, 0) AS INTEGER) AS defense_head,
    CAST(COALESCE(cdl.defense_torso, 0) AS INTEGER) AS defense_torso,
    CAST(COALESCE(cdl.defense_left_arm, 0) AS INTEGER) AS defense_left_arm,
    CAST(COALESCE(cdl.defense_right_arm, 0) AS INTEGER) AS defense_right_arm,
    CAST(COALESCE(cdl.defense_left_leg, 0) AS INTEGER) AS defense_left_leg,
    CAST(COALESCE(cdl.defense_right_leg, 0) AS INTEGER) AS defense_right_leg,
    CAST(COALESCE(crl.damage_resistance_physical_head, 0) AS INTEGER) AS damage_resistance_physical_head,
    CAST(COALESCE(crl.damage_resistance_physical_torso, 0) AS INTEGER) AS damage_resistance_physical_torso,
    CAST(COALESCE(crl.damage_resistance_physical_left_arm, 0) AS INTEGER) AS damage_resistance_physical_left_arm,
    CAST(COALESCE(crl.damage_resistance_physical_right_arm, 0) AS INTEGER) AS damage_resistance_physical_right_arm,
    CAST(COALESCE(crl.damage_resistance_physical_left_leg, 0) AS INTEGER) AS damage_resistance_physical_left_leg,
    CAST(COALESCE(crl.damage_resistance_physical_right_leg, 0) AS INTEGER) AS damage_resistance_physical_right_leg,
    CAST(COALESCE(crg.damage_resistance_physical, 0) AS INTEGER) AS damage_resistance_physical,
    CAST(COALESCE(crg.damage_resistance_energy, 0) AS INTEGER) AS damage_resistance_energy,
    CAST(COALESCE(crg.damage_resistance_radiation, 0) AS INTEGER) AS damage_resistance_radiation,
    CAST(COALESCE(crg.damage_resistance_poison, 0) AS INTEGER) AS damage_resistance_poison,
    CAST(COALESCE(crl.damage_resistance_energy_head, 0) AS INTEGER) AS damage_resistance_energy_head,
    CAST(COALESCE(crl.damage_resistance_energy_torso, 0) AS INTEGER) AS damage_resistance_energy_torso,
    CAST(COALESCE(crl.damage_resistance_energy_left_arm, 0) AS INTEGER) AS damage_resistance_energy_left_arm,
    CAST(COALESCE(crl.damage_resistance_energy_right_arm, 0) AS INTEGER) AS damage_resistance_energy_right_arm,
    CAST(COALESCE(crl.damage_resistance_energy_left_leg, 0) AS INTEGER) AS damage_resistance_energy_left_leg,
    CAST(COALESCE(crl.damage_resistance_energy_right_leg, 0) AS INTEGER) AS damage_resistance_energy_right_leg,
    CAST(COALESCE(crl.damage_resistance_radiation_head, 0) AS INTEGER) AS damage_resistance_radiation_head,
    CAST(COALESCE(crl.damage_resistance_radiation_torso, 0) AS INTEGER) AS damage_resistance_radiation_torso,
    CAST(COALESCE(crl.damage_resistance_radiation_left_arm, 0) AS INTEGER) AS damage_resistance_radiation_left_arm,
    CAST(COALESCE(crl.damage_resistance_radiation_right_arm, 0) AS INTEGER) AS damage_resistance_radiation_right_arm,
    CAST(COALESCE(crl.damage_resistance_radiation_left_leg, 0) AS INTEGER) AS damage_resistance_radiation_left_leg,
    CAST(COALESCE(crl.damage_resistance_radiation_right_leg, 0) AS INTEGER) AS damage_resistance_radiation_right_leg,
    CAST(COALESCE(crg.damage_resistance_physical_immune, 0) AS INTEGER) AS damage_resistance_physical_immune,
    CAST(COALESCE(crg.damage_resistance_energy_immune, 0) AS INTEGER) AS damage_resistance_energy_immune,
    CAST(COALESCE(crg.damage_resistance_radiation_immune, 0) AS INTEGER) AS damage_resistance_radiation_immune,
    CAST(COALESCE(crg.damage_resistance_poison_immune, 0) AS INTEGER) AS damage_resistance_poison_immune,
    ROW_NUMBER() OVER (
      PARTITION BY LOWER(TRIM(c.name))
      ORDER BY e.updated_at DESC, e.id DESC, c.position ASC
    ) AS rn
  FROM combatants c
  JOIN encounters e ON e.id = c.encounter_id
  LEFT JOIN combatant_defense cdl ON cdl.combatant_id = c.id
  LEFT JOIN combatant_resistance_global_agg crg ON crg.combatant_id = c.id
  LEFT JOIN combatant_resistance_by_location_agg crl ON crl.combatant_id = c.id
  WHERE c.side = 'party'
    AND e.deleted_at IS NULL
    AND e.campaign_id = ?1
)
SELECT
  name,
  level,
  xp,
  initiative,
  hp,
  max_hp,
  defense,
  torso_only,
  defense_head,
  defense_torso,
  defense_left_arm,
  defense_right_arm,
  defense_left_leg,
  defense_right_leg,
  damage_resistance_physical_head,
  damage_resistance_physical_torso,
  damage_resistance_physical_left_arm,
  damage_resistance_physical_right_arm,
  damage_resistance_physical_left_leg,
  damage_resistance_physical_right_leg,
  damage_resistance_physical,
  damage_resistance_energy,
  damage_resistance_radiation,
  damage_resistance_poison,
  damage_resistance_energy_head,
  damage_resistance_energy_torso,
  damage_resistance_energy_left_arm,
  damage_resistance_energy_right_arm,
  damage_resistance_energy_left_leg,
  damage_resistance_energy_right_leg,
  damage_resistance_radiation_head,
  damage_resistance_radiation_torso,
  damage_resistance_radiation_left_arm,
  damage_resistance_radiation_right_arm,
  damage_resistance_radiation_left_leg,
  damage_resistance_radiation_right_leg,
  damage_resistance_physical_immune,
  damage_resistance_energy_immune,
  damage_resistance_radiation_immune,
  damage_resistance_poison_immune
FROM latest_party
WHERE rn = 1
ORDER BY name COLLATE NOCASE ASC
`

type ListEncounterPartyTemplatesByCampaignIDRow struct {
	Name                              string
	Level                             int64
	Xp                                int64
	Initiative                        int64
	Hp                                int64
	MaxHp                             int64
	Defense                           int64
	TorsoOnly                         int64
	DefenseHead                       int64
	DefenseTorso                      int64
	DefenseLeftArm                    int64
	DefenseRightArm                   int64
	DefenseLeftLeg                    int64
	DefenseRightLeg                   int64
	DamageResistancePhysicalHead      int64
	DamageResistancePhysicalTorso     int64
	DamageResistancePhysicalLeftArm   int64
	DamageResistancePhysicalRightArm  int64
	DamageResistancePhysicalLeftLeg   int64
	DamageResistancePhysicalRightLeg  int64
	DamageResistancePhysical          int64
	DamageResistanceEnergy            int64
	DamageResistanceRadiation         int64
	DamageResistancePoison            int64
	DamageResistanceEnergyHead        int64
	DamageResistanceEnergyTorso       int64
	DamageResistanceEnergyLeftArm     int64
	DamageResistanceEnergyRightArm    int64
	DamageResistanceEnergyLeftLeg     int64
	DamageResistanceEnergyRightLeg    int64
	DamageResistanceRadiationHead     int64
	DamageResistanceRadiationTorso    int64
	DamageResistanceRadiationLeftArm  int64
	DamageResistanceRadiationRightArm int64
	DamageResistanceRadiationLeftLeg  int64
	DamageResistanceRadiationRightLeg int64
	DamageResistancePhysicalImmune    int64
	DamageResistanceEnergyImmune      int64
	DamageResistanceRadiationImmune   int64
	DamageResistancePoisonImmune      int64
}

func (q *Queries) ListEncounterPartyTemplatesByCampaignID(ctx context.Context, campaignID interface{}) ([]ListEncounterPartyTemplatesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterPartyTemplatesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterPartyTemplatesByCampaignIDRow
	for rows.Next() {
		var i ListEncounterPartyTemplatesByCampaignIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Level,
			&i.Xp,
			&i.Initiative,
			&i.Hp,
			&i.MaxHp,
			&i.Defense,
			&i.TorsoOnly,
			&i.DefenseHead,
			&i.DefenseTorso,
			&i.DefenseLeftArm,
			&i.DefenseRightArm,
			&i.DefenseLeftLeg,
			&i.DefenseRightLeg,
			&i.DamageResistancePhysicalHead,
			&i.DamageResistancePhysicalTorso,
			&i.DamageResistancePhysicalLeftArm,
			&i.DamageResistancePhysicalRightArm,
			&i.DamageResistancePhysicalLeftLeg,
			&i.DamageResistancePhysicalRightLeg,
			&i.DamageResistancePhysical,
			&i.DamageResistanceEnergy,
			&i.DamageResistanceRadiation,
			&i.DamageResistancePoison,
			&i.DamageResistanceEnergyHead,
			&i.DamageResistanceEnergyTorso,
			&i.DamageResistanceEnergyLeftArm,
			&i.DamageResistanceEnergyRightArm,
			&i.DamageResistanceEnergyLeftLeg,
			&i.DamageResistanceEnergyRightLeg,
			&i.DamageResistanceRadiationHead,
			&i.DamageResistanceRadiationTorso,
			&i.DamageResistanceRadiationLeftArm,
			&i.DamageResistanceRadiationRightArm,
			&i.DamageResistanceRadiationLeftLeg,
			&i.DamageResistanceRadiationRightLeg,
			&i.DamageResistancePhysicalImmune,
			&i.DamageResistanceEnergyImmune,
			&i.DamageResistanceRadiationImmune,
			&i.DamageResistancePoisonImmune,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterSummariesByCampaignID = `-- name: ListEncounterSummariesByCampaignID :many
SELECT
  e.id,
  e.campaign_id,
  e.name,
  e.round,
  COUNT(c.id) AS combatants,
  e.difficulty_label,
  e.difficulty_score,
  e.party_count,
  e.party_avg_level,
  e.party_xp_budget,
  e.enemy_count,
  e.enemy_avg_level,
  e.enemy_total_xp,
  e.updated_at
FROM encounters e
LEFT JOIN combatants c ON c.encounter_id = e.id
WHERE e.deleted_at IS NULL AND e.campaign_id = ?1
GROUP BY
  e.id, e.campaign_id, e.name, e.round,
  e.difficulty_label, e.difficulty_score,
  e.party_count, e.party_avg_level, e.party_xp_budget,
  e.enemy_count, e.enemy_avg_level, e.enemy_total_xp,
  e.updated_at
ORDER BY e.updated_at DESC, e.id DESC
`

type ListEncounterSummariesByCampaignIDRow struct {
	ID              string
	CampaignID      interface{}
	Name            string
	Round           int64
	Combatants      int64
	DifficultyLabel string
	DifficultyScore float64
	PartyCount      int64
	PartyAvgLevel   float64
	PartyXpBudget   int64
	EnemyCount      int64
	EnemyAvgLevel   float64
	EnemyTotalXp    int64
	UpdatedAt       time.Time
}

func (q *Queries) ListEncounterSummariesByCampaignID(ctx context.Context, campaignID interface{}) ([]ListEncounterSummariesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterSummariesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterSummariesByCampaignIDRow
	for rows.Next() {
		var i ListEncounterSummariesByCampaignIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Round,
			&i.Combatants,
			&i.DifficultyLabel,
			&i.DifficultyScore,
			&i.PartyCount,
			&i.PartyAvgLevel,
			&i.PartyXpBudget,
			&i.EnemyCount,
			&i.EnemyAvgLevel,
			&i.EnemyTotalXp,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerIDsAndNamesByCampaignID = `-- name: ListPlayerIDsAndNamesByCampaignID :many
SELECT id, name
FROM players
WHERE campaign_id = ?1
`

type ListPlayerIDsAndNamesByCampaignIDRow struct {
	ID   string
	Name string
}

func (q *Queries) ListPlayerIDsAndNamesByCampaignID(ctx context.Context, campaignID string) ([]ListPlayerIDsAndNamesByCampaignIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerIDsAndNamesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerIDsAndNamesByCampaignIDRow
	for rows.Next() {
		var i ListPlayerIDsAndNamesByCampaignIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveCampaign = `-- name: SetActiveCampaign :execrows
UPDATE app_state
SET active_campaign_id = ?1
WHERE id = 1
  AND EXISTS (
    SELECT 1
    FROM campaigns c
    WHERE c.id = ?1
  )
`

func (q *Queries) SetActiveCampaign(ctx context.Context, campaignID interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, setActiveCampaign, campaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteEncounterByCampaign = `-- name: SoftDeleteEncounterByCampaign :execrows
UPDATE encounters
SET deleted_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE encounters.id = ?1 AND encounters.deleted_at IS NULL AND encounters.campaign_id = ?2
`

type SoftDeleteEncounterByCampaignParams struct {
	EncounterID string
	CampaignID  interface{}
}

func (q *Queries) SoftDeleteEncounterByCampaign(ctx context.Context, arg SoftDeleteEncounterByCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncounterByCampaign, arg.EncounterID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchCampaign = `-- name: TouchCampaign :exec
UPDATE campaigns
SET updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?1
`

func (q *Queries) TouchCampaign(ctx context.Context, campaignID string) error {
	_, err := q.db.ExecContext(ctx, touchCampaign, campaignID)
	return err
}

const updateActivePlayerCharacterByID = `-- name: UpdateActivePlayerCharacterByID :exec
UPDATE player_characters
SET campaign_id = ?1,
    name = ?2,
    level = ?3,
    initiative = ?4,
    hp = ?5,
    max_hp = ?6,
    defense = ?7,
    torso_only = ?8,
    active = 1,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?9
`

type UpdateActivePlayerCharacterByIDParams struct {
	CampaignID  string
	Name        string
	Level       int64
	Initiative  int64
	Hp          int64
	MaxHp       int64
	Defense     int64
	TorsoOnly   int64
	CharacterID string
}

func (q *Queries) UpdateActivePlayerCharacterByID(ctx context.Context, arg UpdateActivePlayerCharacterByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateActivePlayerCharacterByID,
		arg.CampaignID,
		arg.Name,
		arg.Level,
		arg.Initiative,
		arg.Hp,
		arg.MaxHp,
		arg.Defense,
		arg.TorsoOnly,
		arg.CharacterID,
	)
	return err
}

const updateCampaignByID = `-- name: UpdateCampaignByID :execrows
UPDATE campaigns
SET name = ?1,
    start_date = ?2,
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE id = ?3
`

type UpdateCampaignByIDParams struct {
	Name       string
	StartDate  string
	CampaignID string
}

func (q *Queries) UpdateCampaignByID(ctx context.Context, arg UpdateCampaignByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCampaignByID, arg.Name, arg.StartDate, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCombatantDefenseByLocation = `-- name: UpsertCombatantDefenseByLocation :exec
INSERT INTO combatant_defense_by_location (
  combatant_id,
  body_location_id,
  defense,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (combatant_id, body_location_id) DO UPDATE SET
  defense = excluded.defense,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertCombatantDefenseByLocationParams struct {
	CombatantID    string
	BodyLocationID int64
	Defense        int64
}

func (q *Queries) UpsertCombatantDefenseByLocation(ctx context.Context, arg UpsertCombatantDefenseByLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCombatantDefenseByLocation, arg.CombatantID, arg.BodyLocationID, arg.Defense)
	return err
}

const upsertCombatantResistanceByLocation = `-- name: UpsertCombatantResistanceByLocation :exec
INSERT INTO combatant_resistance_by_location (
  combatant_id,
  damage_type_id,
  body_location_id,
  resistance,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (combatant_id, damage_type_id, body_location_id) DO UPDATE SET
  resistance = excluded.resistance,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertCombatantResistanceByLocationParams struct {
	CombatantID    string
	DamageTypeID   int64
	BodyLocationID int64
	Resistance     int64
}

func (q *Queries) UpsertCombatantResistanceByLocation(ctx context.Context, arg UpsertCombatantResistanceByLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCombatantResistanceByLocation,
		arg.CombatantID,
		arg.DamageTypeID,
		arg.BodyLocationID,
		arg.Resistance,
	)
	return err
}

const upsertCombatantResistanceGlobal = `-- name: UpsertCombatantResistanceGlobal :exec
INSERT INTO combatant_resistance_global (
  combatant_id,
  damage_type_id,
  resistance,
  immune,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (combatant_id, damage_type_id) DO UPDATE SET
  resistance = excluded.resistance,
  immune = excluded.immune,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertCombatantResistanceGlobalParams struct {
	CombatantID  string
	DamageTypeID int64
	Resistance   int64
	Immune       int64
}

func (q *Queries) UpsertCombatantResistanceGlobal(ctx context.Context, arg UpsertCombatantResistanceGlobalParams) error {
	_, err := q.db.ExecContext(ctx, upsertCombatantResistanceGlobal,
		arg.CombatantID,
		arg.DamageTypeID,
		arg.Resistance,
		arg.Immune,
	)
	return err
}

const upsertEncounter = `-- name: UpsertEncounter :exec
INSERT INTO encounters (
  id, campaign_id, name, round, turn_index, party_ap, gm_threat,
  difficulty_label, difficulty_score,
  party_count, party_avg_level, party_xp_budget,
  enemy_count, enemy_avg_level, enemy_total_xp,
  created_at, updated_at, deleted_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  NULL
)
ON CONFLICT(id) DO UPDATE SET
	campaign_id = excluded.campaign_id,
	name = excluded.name,
	round = excluded.round,
	turn_index = excluded.turn_index,
	party_ap = excluded.party_ap,
	gm_threat = excluded.gm_threat,
	difficulty_label = excluded.difficulty_label,
	difficulty_score = excluded.difficulty_score,
	party_count = excluded.party_count,
	party_avg_level = excluded.party_avg_level,
	party_xp_budget = excluded.party_xp_budget,
	enemy_count = excluded.enemy_count,
	enemy_avg_level = excluded.enemy_avg_level,
	enemy_total_xp = excluded.enemy_total_xp,
	deleted_at = NULL,
	updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertEncounterParams struct {
	ID              string
	CampaignID      interface{}
	Name            string
	Round           int64
	TurnIndex       int64
	PartyAp         int64
	GmThreat        int64
	DifficultyLabel string
	DifficultyScore float64
	PartyCount      int64
	PartyAvgLevel   float64
	PartyXpBudget   int64
	EnemyCount      int64
	EnemyAvgLevel   float64
	EnemyTotalXp    int64
}

func (q *Queries) UpsertEncounter(ctx context.Context, arg UpsertEncounterParams) error {
	_, err := q.db.ExecContext(ctx, upsertEncounter,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.Round,
		arg.TurnIndex,
		arg.PartyAp,
		arg.GmThreat,
		arg.DifficultyLabel,
		arg.DifficultyScore,
		arg.PartyCount,
		arg.PartyAvgLevel,
		arg.PartyXpBudget,
		arg.EnemyCount,
		arg.EnemyAvgLevel,
		arg.EnemyTotalXp,
	)
	return err
}

const upsertPlayerCharacterDefenseByLocation = `-- name: UpsertPlayerCharacterDefenseByLocation :exec
INSERT INTO player_character_defense_by_location (
  player_character_id,
  body_location_id,
  defense,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (player_character_id, body_location_id) DO UPDATE SET
  defense = excluded.defense,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertPlayerCharacterDefenseByLocationParams struct {
	PlayerCharacterID string
	BodyLocationID    int64
	Defense           int64
}

func (q *Queries) UpsertPlayerCharacterDefenseByLocation(ctx context.Context, arg UpsertPlayerCharacterDefenseByLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCharacterDefenseByLocation, arg.PlayerCharacterID, arg.BodyLocationID, arg.Defense)
	return err
}

const upsertPlayerCharacterResistanceByLocation = `-- name: UpsertPlayerCharacterResistanceByLocation :exec
INSERT INTO player_character_resistance_by_location (
  player_character_id,
  damage_type_id,
  body_location_id,
  resistance,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (player_character_id, damage_type_id, body_location_id) DO UPDATE SET
  resistance = excluded.resistance,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertPlayerCharacterResistanceByLocationParams struct {
	PlayerCharacterID string
	DamageTypeID      int64
	BodyLocationID    int64
	Resistance        int64
}

func (q *Queries) UpsertPlayerCharacterResistanceByLocation(ctx context.Context, arg UpsertPlayerCharacterResistanceByLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCharacterResistanceByLocation,
		arg.PlayerCharacterID,
		arg.DamageTypeID,
		arg.BodyLocationID,
		arg.Resistance,
	)
	return err
}

const upsertPlayerCharacterResistanceGlobal = `-- name: UpsertPlayerCharacterResistanceGlobal :exec
INSERT INTO player_character_resistance_global (
  player_character_id,
  damage_type_id,
  resistance,
  immune,
  updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
ON CONFLICT (player_character_id, damage_type_id) DO UPDATE SET
  resistance = excluded.resistance,
  immune = excluded.immune,
  updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertPlayerCharacterResistanceGlobalParams struct {
	PlayerCharacterID string
	DamageTypeID      int64
	Resistance        int64
	Immune            int64
}

func (q *Queries) UpsertPlayerCharacterResistanceGlobal(ctx context.Context, arg UpsertPlayerCharacterResistanceGlobalParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCharacterResistanceGlobal,
		arg.PlayerCharacterID,
		arg.DamageTypeID,
		arg.Resistance,
		arg.Immune,
	)
	return err
}
