// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package dbgen

import (
	"context"
	"time"
)

const activateEncounter = `-- name: ActivateEncounter :execrows
UPDATE encounters
SET updated_at = CASE
  WHEN STRFTIME('%Y-%m-%d %H:%M:%f', 'now') <= COALESCE((SELECT MAX(updated_at) FROM encounters WHERE deleted_at IS NULL), '')
    THEN STRFTIME(
      '%Y-%m-%d %H:%M:%f',
      COALESCE((SELECT MAX(updated_at) FROM encounters WHERE deleted_at IS NULL), STRFTIME('%Y-%m-%d %H:%M:%f', 'now')),
      '+0.001 seconds'
    )
  ELSE STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
END
WHERE encounters.id = ?1 AND deleted_at IS NULL
`

func (q *Queries) ActivateEncounter(ctx context.Context, encounterID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateEncounter, encounterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCombatantsByEncounterID = `-- name: DeleteCombatantsByEncounterID :exec
DELETE FROM combatants
WHERE encounter_id = ?1
`

func (q *Queries) DeleteCombatantsByEncounterID(ctx context.Context, encounterID string) error {
	_, err := q.db.ExecContext(ctx, deleteCombatantsByEncounterID, encounterID)
	return err
}

const getLatestEncounter = `-- name: GetLatestEncounter :one
SELECT id, name, round, turn_index, party_ap, gm_threat
FROM encounters
WHERE deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetLatestEncounterRow struct {
	ID        string
	Name      string
	Round     int64
	TurnIndex int64
	PartyAp   int64
	GmThreat  int64
}

func (q *Queries) GetLatestEncounter(ctx context.Context) (GetLatestEncounterRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestEncounter)
	var i GetLatestEncounterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Round,
		&i.TurnIndex,
		&i.PartyAp,
		&i.GmThreat,
	)
	return i, err
}

const insertCombatant = `-- name: InsertCombatant :exec
INSERT INTO combatants (
	id, encounter_id, name, side, level, xp, initiative, hp, defense,
	damage_resistance, damage_resistance_physical, damage_resistance_energy, damage_resistance_radiation, damage_resistance_poison,
	damage_resistance_physical_immune, damage_resistance_energy_immune, damage_resistance_radiation_immune, damage_resistance_poison_immune,
	active, defeated, position
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17,
  ?18,
  ?19,
  ?20,
  ?21
)
`

type InsertCombatantParams struct {
	ID                              string
	EncounterID                     string
	Name                            string
	Side                            string
	Level                           int64
	Xp                              int64
	Initiative                      int64
	Hp                              int64
	Defense                         int64
	DamageResistance                int64
	DamageResistancePhysical        int64
	DamageResistanceEnergy          int64
	DamageResistanceRadiation       int64
	DamageResistancePoison          int64
	DamageResistancePhysicalImmune  int64
	DamageResistanceEnergyImmune    int64
	DamageResistanceRadiationImmune int64
	DamageResistancePoisonImmune    int64
	Active                          int64
	Defeated                        int64
	Position                        int64
}

func (q *Queries) InsertCombatant(ctx context.Context, arg InsertCombatantParams) error {
	_, err := q.db.ExecContext(ctx, insertCombatant,
		arg.ID,
		arg.EncounterID,
		arg.Name,
		arg.Side,
		arg.Level,
		arg.Xp,
		arg.Initiative,
		arg.Hp,
		arg.Defense,
		arg.DamageResistance,
		arg.DamageResistancePhysical,
		arg.DamageResistanceEnergy,
		arg.DamageResistanceRadiation,
		arg.DamageResistancePoison,
		arg.DamageResistancePhysicalImmune,
		arg.DamageResistanceEnergyImmune,
		arg.DamageResistanceRadiationImmune,
		arg.DamageResistancePoisonImmune,
		arg.Active,
		arg.Defeated,
		arg.Position,
	)
	return err
}

const insertEncounterLog = `-- name: InsertEncounterLog :exec
INSERT INTO encounter_logs (encounter_id, round, message, created_at)
VALUES (
  ?1,
  ?2,
  ?3,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
)
`

type InsertEncounterLogParams struct {
	EncounterID string
	Round       int64
	Message     string
}

func (q *Queries) InsertEncounterLog(ctx context.Context, arg InsertEncounterLogParams) error {
	_, err := q.db.ExecContext(ctx, insertEncounterLog, arg.EncounterID, arg.Round, arg.Message)
	return err
}

const listCombatantsByEncounterID = `-- name: ListCombatantsByEncounterID :many
SELECT id, name, side, level, xp, initiative, hp, defense,
       damage_resistance_physical, damage_resistance_energy, damage_resistance_radiation, damage_resistance_poison,
       damage_resistance_physical_immune, damage_resistance_energy_immune, damage_resistance_radiation_immune, damage_resistance_poison_immune,
       active, defeated
FROM combatants
WHERE encounter_id = ?1
ORDER BY position ASC
`

type ListCombatantsByEncounterIDRow struct {
	ID                              string
	Name                            string
	Side                            string
	Level                           int64
	Xp                              int64
	Initiative                      int64
	Hp                              int64
	Defense                         int64
	DamageResistancePhysical        int64
	DamageResistanceEnergy          int64
	DamageResistanceRadiation       int64
	DamageResistancePoison          int64
	DamageResistancePhysicalImmune  int64
	DamageResistanceEnergyImmune    int64
	DamageResistanceRadiationImmune int64
	DamageResistancePoisonImmune    int64
	Active                          int64
	Defeated                        int64
}

func (q *Queries) ListCombatantsByEncounterID(ctx context.Context, encounterID string) ([]ListCombatantsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCombatantsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatantsByEncounterIDRow
	for rows.Next() {
		var i ListCombatantsByEncounterIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Side,
			&i.Level,
			&i.Xp,
			&i.Initiative,
			&i.Hp,
			&i.Defense,
			&i.DamageResistancePhysical,
			&i.DamageResistanceEnergy,
			&i.DamageResistanceRadiation,
			&i.DamageResistancePoison,
			&i.DamageResistancePhysicalImmune,
			&i.DamageResistanceEnergyImmune,
			&i.DamageResistanceRadiationImmune,
			&i.DamageResistancePoisonImmune,
			&i.Active,
			&i.Defeated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterLogsByEncounterID = `-- name: ListEncounterLogsByEncounterID :many
SELECT round, message, created_at
FROM encounter_logs
WHERE encounter_id = ?1
ORDER BY created_at DESC, id DESC
`

type ListEncounterLogsByEncounterIDRow struct {
	Round     int64
	Message   string
	CreatedAt time.Time
}

func (q *Queries) ListEncounterLogsByEncounterID(ctx context.Context, encounterID string) ([]ListEncounterLogsByEncounterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterLogsByEncounterID, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterLogsByEncounterIDRow
	for rows.Next() {
		var i ListEncounterLogsByEncounterIDRow
		if err := rows.Scan(&i.Round, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterSummaries = `-- name: ListEncounterSummaries :many
SELECT e.id, e.name, e.round, COUNT(c.id) AS combatants, e.updated_at
FROM encounters e
LEFT JOIN combatants c ON c.encounter_id = e.id
WHERE e.deleted_at IS NULL
GROUP BY e.id, e.name, e.round, e.updated_at
ORDER BY e.updated_at DESC, e.id DESC
`

type ListEncounterSummariesRow struct {
	ID         string
	Name       string
	Round      int64
	Combatants int64
	UpdatedAt  time.Time
}

func (q *Queries) ListEncounterSummaries(ctx context.Context) ([]ListEncounterSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncounterSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterSummariesRow
	for rows.Next() {
		var i ListEncounterSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Round,
			&i.Combatants,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEncounter = `-- name: SoftDeleteEncounter :execrows
UPDATE encounters
SET deleted_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
    updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
WHERE encounters.id = ?1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEncounter(ctx context.Context, encounterID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncounter, encounterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEncounter = `-- name: UpsertEncounter :exec
INSERT INTO encounters (id, name, round, turn_index, party_ap, gm_threat, updated_at, deleted_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  STRFTIME('%Y-%m-%d %H:%M:%f', 'now'),
  NULL
)
ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	round = excluded.round,
	turn_index = excluded.turn_index,
	party_ap = excluded.party_ap,
	gm_threat = excluded.gm_threat,
	deleted_at = NULL,
	updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'now')
`

type UpsertEncounterParams struct {
	ID        string
	Name      string
	Round     int64
	TurnIndex int64
	PartyAp   int64
	GmThreat  int64
}

func (q *Queries) UpsertEncounter(ctx context.Context, arg UpsertEncounterParams) error {
	_, err := q.db.ExecContext(ctx, upsertEncounter,
		arg.ID,
		arg.Name,
		arg.Round,
		arg.TurnIndex,
		arg.PartyAp,
		arg.GmThreat,
	)
	return err
}
