package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	_ "modernc.org/sqlite"

	"github.com/pressly/goose/v3"
)

type schemaObject struct {
	Type string
	Name string
	SQL  string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "generate schema: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	migrationsDir := flag.String("migrations", "internal/store/sqlite/migrations", "directory with goose migrations")
	outPath := flag.String("out", "internal/store/sqlite/sqlc/schema.sql", "schema.sql output path")
	flag.Parse()

	log.Printf("using migrations dir: %s", *migrationsDir)
	log.Printf("schema output path: %s", *outPath)

	tmpDir, err := os.MkdirTemp("", "fallout-schema-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer func() {
		_ = os.RemoveAll(tmpDir)
	}()

	dbPath := filepath.Join(tmpDir, "schema.db")
	log.Printf("creating clean sqlite database: %s", dbPath)
	db, err := sql.Open("sqlite", sqliteDSN(dbPath))
	if err != nil {
		return fmt.Errorf("open sqlite db: %w", err)
	}
	defer func() {
		_ = db.Close()
	}()

	if _, err := db.Exec(`PRAGMA foreign_keys = ON;`); err != nil {
		return fmt.Errorf("enable foreign keys: %w", err)
	}
	if err := goose.SetDialect("sqlite3"); err != nil {
		return fmt.Errorf("set goose dialect: %w", err)
	}
	log.Printf("applying migrations")
	if err := goose.Up(db, *migrationsDir); err != nil {
		return fmt.Errorf("run migrations: %w", err)
	}
	log.Printf("migrations applied")

	schema, err := buildSchema(db)
	if err != nil {
		return err
	}
	log.Printf("writing generated schema")
	if err := writeFileAtomic(*outPath, []byte(schema)); err != nil {
		return err
	}
	log.Printf("schema generated successfully: %s", *outPath)
	return nil
}

func buildSchema(db *sql.DB) (string, error) {
	objects, err := listSchemaObjects(db)
	if err != nil {
		return "", err
	}
	log.Printf("rendering schema objects: %d", len(objects))

	var b strings.Builder
	b.WriteString("-- Code generated by make schema-generate; DO NOT EDIT.\n")
	b.WriteString("-- Source of truth: internal/store/sqlite/migrations/*.sql applied to a clean SQLite database.\n\n")

	for _, object := range objects {
		writeStatement(&b, object.SQL)
		if object.Type == "table" && isEnumTable(object.Name) {
			if err := writeEnumRows(&b, db, object.Name); err != nil {
				return "", err
			}
		}
	}

	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

func listSchemaObjects(db *sql.DB) ([]schemaObject, error) {
	rows, err := db.Query(`
SELECT type, name, sql
FROM sqlite_schema
WHERE sql IS NOT NULL
  AND type IN ('table', 'view', 'index', 'trigger')
  AND name NOT LIKE 'sqlite_%'
  AND name <> 'goose_db_version'
  AND tbl_name <> 'goose_db_version'
ORDER BY
  CASE type
    WHEN 'table' THEN 1
    WHEN 'view' THEN 2
    WHEN 'index' THEN 3
    WHEN 'trigger' THEN 4
    ELSE 5
  END,
  rowid`)
	if err != nil {
		return nil, fmt.Errorf("query sqlite schema: %w", err)
	}
	defer func() {
		_ = rows.Close()
	}()

	var objects []schemaObject
	for rows.Next() {
		var object schemaObject
		if err := rows.Scan(&object.Type, &object.Name, &object.SQL); err != nil {
			return nil, fmt.Errorf("scan schema object: %w", err)
		}
		objects = append(objects, object)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate schema objects: %w", err)
	}
	return objects, nil
}

func writeEnumRows(b *strings.Builder, db *sql.DB, table string) error {
	rows, err := db.Query(fmt.Sprintf("SELECT id, code FROM %s ORDER BY id", table))
	if err != nil {
		return fmt.Errorf("query enum table %s: %w", table, err)
	}
	defer func() {
		_ = rows.Close()
	}()

	type enumRow struct {
		id   int64
		code string
	}
	var values []enumRow
	for rows.Next() {
		var value enumRow
		if err := rows.Scan(&value.id, &value.code); err != nil {
			return fmt.Errorf("scan enum table %s: %w", table, err)
		}
		values = append(values, value)
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate enum table %s: %w", table, err)
	}
	if len(values) == 0 {
		log.Printf("enum table %s has no seed rows", table)
		return nil
	}
	log.Printf("rendering enum seed rows: table=%s rows=%d", table, len(values))

	b.WriteString("INSERT OR IGNORE INTO ")
	b.WriteString(table)
	b.WriteString(" (id, code) VALUES\n")
	for i, value := range values {
		b.WriteString("    (")
		b.WriteString(strconv.FormatInt(value.id, 10))
		b.WriteString(", ")
		b.WriteString(sqlString(value.code))
		b.WriteString(")")
		if i == len(values)-1 {
			b.WriteString(";\n\n")
		} else {
			b.WriteString(",\n")
		}
	}
	return nil
}

func writeStatement(b *strings.Builder, sql string) {
	stmt := strings.TrimSpace(sql)
	stmt = strings.TrimRight(stmt, ";")
	b.WriteString(stmt)
	b.WriteString(";\n\n")
}

func isEnumTable(name string) bool {
	return name == "body_locations" || name == "damage_types"
}

func sqlString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func sqliteDSN(dbPath string) string {
	u := url.URL{
		Scheme: "file",
		Path:   dbPath,
	}
	q := u.Query()
	q.Add("_pragma", "foreign_keys(1)")
	u.RawQuery = q.Encode()
	return u.String()
}

func writeFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, data, 0o644); err != nil {
		return fmt.Errorf("write temp schema: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("replace schema: %w", err)
	}
	return nil
}
